(defpackage :ptui.test.scroll-util
  (:use :cl :fiveam)
  (:export #:scroll-util-suite))

(in-package :ptui.test.scroll-util)

(def-suite scroll-util-suite
  :description "Shared PTUI scroll utility tests.")

(in-suite scroll-util-suite)

(test scroll-utility-clamps-to-viewport-window
  (is (= 15 (ptui.util.scroll:max-scroll-offset 20 5)))
  (is (= 15 (ptui.util.scroll:clamp-scroll-offset 999 20 5)))
  (is (= 0 (ptui.util.scroll:clamp-scroll-offset -3 20 5)))
  (is (= 3 (ptui.util.scroll:apply-scroll-delta 0 3 20 5)))
  (is (= 0 (ptui.util.scroll:apply-scroll-delta 3 -99 20 5)))
  (is (= 15 (ptui.util.scroll:render-scroll-offset 0 20 5)))
  (is (= 12 (ptui.util.scroll:render-scroll-offset 3 20 5)))
  (is (= 3 (ptui.util.scroll:render-scroll-offset 3 20 5 :origin :top))))

(test scroll-utility-normalizes-key-aliases-and-direction
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :up :viewport-height 12)
    (is (eq :delta action))
    (is (= 1 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :down :viewport-height 12)
    (is (eq :delta action))
    (is (= -1 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :pgup :viewport-height 12)
    (is (eq :delta action))
    (is (= 11 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :page-up :viewport-height 12)
    (is (eq :delta action))
    (is (= 11 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :pgdn :viewport-height 12)
    (is (eq :delta action))
    (is (= -11 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :page-down :viewport-height 12)
    (is (eq :delta action))
    (is (= -11 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :up :viewport-height 12 :origin :top)
    (is (eq :delta action))
    (is (= -1 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :down :viewport-height 12 :origin :top)
    (is (eq :delta action))
    (is (= 1 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :pgup :viewport-height 12 :origin :top)
    (is (eq :delta action))
    (is (= -11 delta)))
  (multiple-value-bind (action delta)
      (ptui.util.scroll:key-scroll-action :pgdn :viewport-height 12 :origin :top)
    (is (eq :delta action))
    (is (= 11 delta))))
