(in-package :amoebum)

(defun %resolve-search-root (root)
  (let* ((candidate
           (cond
             ((null root) (config-project-root (current-config)))
             ((pathnamep root) root)
             ((stringp root) (pathname root))
             (t (error "ROOT must be a pathname, string, or NIL. Got ~S." root))))
         (resolved (or (ignore-errors (truename candidate)) candidate))
         (directory (uiop:ensure-directory-pathname resolved)))
    (unless (probe-file directory)
      (error "Search root does not exist: ~A" (%path-text directory)))
    directory))

(defun %ensure-non-negative-integer (name value)
  (when (and value (< value 0))
    (error "~A must be non-negative, got ~S." name value))
  value)

(defun %recursive-glob-pattern-p (pattern)
  (not (null (search "**" pattern :test #'char=))))

(defun %normalized-path-text (path)
  (%normalize-slashes (%path-text path)))

(defun %relative-path-text (path root)
  (let ((relative (%normalize-slashes (enough-namestring path root))))
    (if (uiop:string-prefix-p "./" relative)
        (subseq relative 2)
        relative)))

(defun %path-mtime (path)
  (or (ignore-errors (file-write-date path)) 0))

(defun %regular-file-p (path)
  (let ((probed (probe-file path)))
    (and probed
         (not (uiop:directory-pathname-p probed)))))

(defun %collect-files-recursive (root)
  (let ((visited (make-hash-table :test #'equal))
        (results '()))
    (labels ((directory-key (directory)
               (let* ((resolved (or (ignore-errors (truename directory)) directory))
                      (as-dir (uiop:ensure-directory-pathname resolved)))
                 (%normalized-path-text as-dir)))
             (walk (directory)
               (let ((key (directory-key directory)))
                 (unless (gethash key visited)
                   (setf (gethash key visited) t)
                   (dolist (file (or (ignore-errors (uiop:directory-files directory)) '()))
                     (push file results))
                   (dolist (subdir (or (ignore-errors (uiop:subdirectories directory)) '()))
                     (walk subdir))))))
      (walk root))
    results))

(defun %glob-candidates (root pattern)
  (if (%recursive-glob-pattern-p pattern)
      (%collect-files-recursive root)
      (or (ignore-errors
            (directory (merge-pathnames (pathname pattern) root)))
          '())))

(defun %matching-files-sorted (tool root pattern &key limit)
  (let* ((scanner (cl-ppcre:create-scanner (%glob->regex pattern)))
         (seen (make-hash-table :test #'equal))
         (matches '()))
    (dolist (candidate (%glob-candidates root pattern))
      (when (%regular-file-p candidate)
        (let* ((resolved (or (ignore-errors (truename candidate)) candidate))
               (key (%normalized-path-text resolved))
               (relative (%relative-path-text resolved root)))
          (unless (gethash key seen)
            (setf (gethash key seen) t)
            (when (cl-ppcre:scan scanner relative)
              (%ensure-tool-path-allowed tool resolved)
              (push resolved matches))))))
    (let ((sorted (sort matches #'> :key #'%path-mtime)))
      (if limit
          (subseq sorted 0 (min limit (length sorted)))
          sorted))))

(defun %line-context (line-vector start end)
  (loop for index from start below end
        collect (list :line (1+ index)
                      :text (aref line-vector index))))

(defun %grep-matches-for-file (file scanner before after root)
  (let* ((lines (handler-case
                    (coerce (%read-lines file) 'vector)
                  (error () #())))
         (line-count (length lines))
         (results '()))
    (loop for index from 0 below line-count do
          (let ((line (aref lines index)))
            (when (cl-ppcre:scan scanner line)
              (let* ((before-start (max 0 (- index before)))
                     (after-end (min line-count (+ index after 1)))
                     (before-context (%line-context lines before-start index))
                     (after-context (%line-context lines (1+ index) after-end)))
                (push (list :path (%path-text file)
                            :relative-path (%relative-path-text file root)
                            :modified-at (%path-mtime file)
                            :line (1+ index)
                            :text line
                            :context-before before-context
                            :context-after after-context)
                      results)))))
    (nreverse results)))

(defun %grep-matches (files scanner before after limit root)
  (let ((matches '())
        (count 0))
    (dolist (file files)
      (dolist (entry (%grep-matches-for-file file scanner before after root))
        (when (and limit (>= count limit))
          (return-from %grep-matches (nreverse matches)))
        (push entry matches)
        (incf count)))
    (nreverse matches)))

(deftool glob-files ((pattern string :description "Glob pattern to match" :required t)
                     (root (or null pathname) :description "Search root directory" :default nil)
                     (limit (or null integer) :description "Maximum results to return" :default 200))
  "Find files matching glob patterns and return results sorted by modification time."
  (:permission :auto)
  (:dangerous nil)
  (:category :search)
  (:timeout 30)
  (%ensure-non-negative-integer "LIMIT" limit)
  (let* ((root-path (%resolve-search-root root))
         (matches (%matching-files-sorted :glob-files root-path pattern :limit limit)))
    (list :root (%path-text root-path)
          :pattern pattern
          :count (length matches)
          :matches
          (mapcar (lambda (path)
                    (list :path (%path-text path)
                          :relative-path (%relative-path-text path root-path)
                          :modified-at (%path-mtime path)))
                  matches))))

(deftool grep-content ((pattern string :description "Regular expression to search for" :required t)
                       (path-glob string :description "Glob filter for candidate files" :default "**/*")
                       (root (or null pathname) :description "Search root directory" :default nil)
                       (before integer :description "Context lines before each match" :default 0)
                       (after integer :description "Context lines after each match" :default 0)
                       (limit (or null integer) :description "Maximum matches to return" :default 200)
                       (case-insensitive boolean :description "Enable case-insensitive regex matching" :default nil))
  "Search file contents with regex and include line-numbered context for each match."
  (:permission :auto)
  (:dangerous nil)
  (:category :search)
  (:timeout 60)
  (%ensure-non-negative-integer "BEFORE" before)
  (%ensure-non-negative-integer "AFTER" after)
  (%ensure-non-negative-integer "LIMIT" limit)
  (let* ((root-path (%resolve-search-root root))
         (files (%matching-files-sorted :grep-content root-path path-glob :limit nil))
         (scanner (cl-ppcre:create-scanner pattern
                                           :case-insensitive-mode case-insensitive))
         (matches (%grep-matches files scanner before after limit root-path)))
    (list :root (%path-text root-path)
          :pattern pattern
          :path-glob path-glob
          :count (length matches)
          :matches matches)))
