(defpackage :pseudopod
  (:use :cl)
  (:nicknames :moonshot-common-lisp)
  (:shadow #:step #:delete-file)
  (:export
   #:*default-base-url*
   #:*default-model*
   #:*default-api-key-file*
   #:client
   #:make-client
   #:client-api-key
   #:client-base-url
   #:client-model
   #:client-temperature
   #:client-max-tokens
   #:client-top-p
   #:client-timeout-seconds
   #:client-max-response-bytes
   #:*default-max-response-bytes*
   #:read-api-key
   #:pseudopod-error
   #:pseudopod-error-message
   #:pseudopod-error-cause
   #:pseudopod-auth-error
   #:pseudopod-timeout-error
   #:pseudopod-api-error
   #:pseudopod-api-error-status-code
   #:pseudopod-api-error-body
   #:pseudopod-parse-error
   #:pseudopod-parse-error-payload
   #:extract-content
   #:extract-role
   #:extract-usage
   #:content-part
   #:content-part-p
   #:content-part-type
   #:content-part-text
   #:content-part-think
   #:content-part-encrypted
   #:content-part-payload
   #:make-text-part
   #:make-think-part
   #:content-part-to-hash
   #:hash-to-content-part
   #:tool-call
   #:tool-call-p
   #:tool-call-id
   #:tool-call-name
   #:tool-call-arguments
   #:tool-call-extras
   #:make-tool-call
   #:tool-call-to-hash
   #:hash-to-tool-call
   #:message
   #:message-p
   #:make-message
   #:message-role
   #:message-name
   #:message-content
   #:message-tool-calls
   #:message-tool-call-id
   #:message-partial
   #:message-to-hash
   #:hash-to-message
   #:model-info
   #:model-info-p
   #:model-info-id
   #:model-info-object
   #:model-info-created-at
   #:model-info-owned-by
   #:model-info-permission
   #:model-info-extras
   #:hash-to-model-info
   #:file-object
   #:file-object-p
   #:file-object-id
   #:file-object-object
   #:file-object-filename
   #:file-object-bytes
   #:file-object-created-at
   #:file-object-purpose
   #:file-object-status
   #:file-object-status-details
   #:file-object-extras
   #:hash-to-file-object
   #:tool-definition
   #:tool-definition-p
   #:make-tool-definition
   #:tool-definition-name
   #:tool-definition-description
   #:tool-definition-parameters
   #:tool-definition-fn
   #:tool-definition-to-hash
   #:toolset
   #:toolset-p
   #:make-toolset
   #:register-tool
   #:register-tool-function
   #:find-tool
   #:toolset-tools
   #:invoke-tool-call
   #:generate-result
   #:generate-result-p
   #:generate-result-id
   #:generate-result-message
   #:generate-result-usage
   #:generate-result-response
   #:step-result
   #:step-result-p
   #:step-result-steps
   #:step-result-history
   #:step-result-final-message
   #:step-result-last-message
   #:step-result-max-steps-reached
   #:step-result-tool-results
   #:generate
   #:step
   #:conversation
   #:conversation-p
   #:make-conversation
   #:conversation-client
   #:conversation-system-prompt
   #:conversation-history
   #:conversation-toolset
   #:conversation-add-user
   #:conversation-add-assistant
   #:conversation-add-tool-result
   #:conversation-complete
   #:conversation-step
   #:conversation-clear
   #:chat-completion
   #:chat-completion*
   #:list-models
   #:estimate-tokens
   #:upload-file
   #:get-file
   #:list-files
   #:delete-file
   #:file-content
   #:stream-chat-completion
   #:stream-chat-completion*
   #:print-streamed-completion
   #:main
   ;; Provider protocol (I94)
   #:provider
   #:provider-name
   #:provider-api-key
   #:provider-base-url
   #:provider-default-model
   #:provider-timeout-seconds
   #:provider-healthy-p
   #:provider-last-error
   #:provider-request-count
   #:provider-error-count
   #:provider-last-latency-ms
   #:provider-error-rate
   #:provider-record-request
   #:send-chat-completion
   #:send-streaming-completion
   #:list-provider-models
   #:estimate-provider-tokens
   #:provider-health-check
   #:with-provider
   #:current-provider
   #:*current-provider*
   ;; Kimi provider
   #:kimi-provider
   #:make-kimi-provider
   #:kimi-provider-client
   ;; Anthropic provider
   #:anthropic-provider
   #:make-anthropic-provider
   #:anthropic-provider-api-version
   #:anthropic-provider-beta-features
   ;; OpenAI-compatible provider
   #:openai-compatible-provider
   #:make-openai-compatible-provider
   #:openai-compat-organization
   ;; Model router (I95)
   #:model-router
   #:model-router-p
   #:make-model-router
   #:model-router-strategy
   #:model-router-providers
   #:model-router-max-retries
   #:router-add-provider
   #:router-remove-provider
   #:router-find-provider
   #:router-healthy-providers
   #:router-select-provider
   #:router-set-task-route
   #:router-chat-completion
   #:router-streaming-completion
   #:router-check-health
   #:router-status
   ;; File read primitive (I103)
   #:pseudopod-file-error
   #:pseudopod-file-error-path
   #:pseudopod-file-not-found
   #:file-read-result
   #:file-read-result-p
   #:file-read-result-content
   #:file-read-result-path
   #:file-read-result-size
   #:file-read-result-modification-time
   #:file-read-result-encoding
   #:read-file
   ;; Structured file read (I104)
   #:structured-read-result
   #:structured-read-result-p
   #:structured-read-result-content
   #:structured-read-result-path
   #:structured-read-result-lines
   #:structured-read-result-bytes
   #:structured-read-result-truncated
   #:read-file-lines
   #:read-file-bytes
   #:read-file-bounded
   ;; Whole-file write primitive (I106)
   #:pseudopod-write-error
   #:pseudopod-write-error-path
   #:write-file
   #:write-result
   #:write-result-p
   #:write-result-path
   #:write-result-bytes
   #:write-result-created-p
   #:write-result-encoding
   ;; String-replace edit primitive (I108)
   #:pseudopod-edit-error
   #:pseudopod-edit-error-path
   #:pseudopod-edit-no-match
   #:pseudopod-edit-ambiguous
   #:pseudopod-edit-ambiguous-match-count
   #:string-replace-result
   #:string-replace-result-p
   #:string-replace-result-path
   #:string-replace-result-match-count
   #:string-replace-result-replaced
   #:string-replace-result-old-string
   #:string-replace-result-new-string
   #:string-replace-in-file
   ;; Command execution primitive (I110)
   #:pseudopod-command-error
   #:pseudopod-command-error-command
   #:pseudopod-command-timeout
   #:pseudopod-command-timeout-seconds
   #:command-result
   #:command-result-p
   #:command-result-stdout
   #:command-result-stderr
   #:command-result-exit-code
   #:command-result-duration-ms
   #:command-result-command
   #:run-command
   #:*default-command-timeout*
   ;; Fetch backend adapter (I123 foundation)
   #:pseudopod-fetch-error
   #:pseudopod-fetch-error-status-code
   #:pseudopod-fetch-error-url
   #:fetch-response
   #:fetch-response-p
   #:fetch-response-url
   #:fetch-response-effective-url
   #:fetch-response-status
   #:fetch-response-body
   #:fetch-response-content-type
   #:fetch-response-fetched-at
   #:fetch-backend
   #:*default-fetch-timeout-seconds*
   #:*default-fetch-user-agent*
   ;; Search backend adapter (I121)
   #:pseudopod-search-error
   #:pseudopod-search-error-backend
   #:pseudopod-search-error-status-code
   #:pseudopod-search-error-url
   #:pseudopod-search-parse-error
   #:pseudopod-search-parse-error-payload
   #:search-hit
   #:search-hit-p
   #:search-hit-title
   #:search-hit-url
   #:search-hit-snippet
   #:search-hit-source-domain
   #:search-hit-rank
   #:search-response
   #:search-response-p
   #:search-response-backend
   #:search-response-query
   #:search-response-results
   #:search-response-result-count
   #:search-response-fetched-at
   #:search-backend
   #:*default-search-timeout-seconds*
   #:*default-search-rate-limit-seconds*
   #:*default-search-user-agent*
   #:*default-duckduckgo-search-url*
   ;; Fetch engine (I123)
   #:pseudopod-fetch-error
   #:pseudopod-fetch-error-url
   #:pseudopod-fetch-error-status-code
   #:pseudopod-fetch-error-effective-url
   #:pseudopod-fetch-timeout
   #:pseudopod-fetch-timeout-seconds
   #:pseudopod-fetch-http-error
   #:pseudopod-fetch-http-error-body
   #:pseudopod-fetch-http-error-content-type
   #:fetch-result
   #:fetch-result-p
   #:fetch-result-url
   #:fetch-result-effective-url
   #:fetch-result-status-code
   #:fetch-result-content-type
   #:fetch-result-body
   #:fetch-result-body-bytes
   #:fetch-result-truncated-p
   #:fetch-result-redirected-p
   #:fetch-result-host-changed-p
   #:fetch-result-cached-p
   #:fetch-result-fetched-at
   #:fetch-url
   #:*default-fetch-timeout-seconds*
   #:*default-fetch-cache-ttl-seconds*
   #:*default-fetch-max-body-bytes*
   #:*default-fetch-user-agent*))
