;;; I298: prompt-input-panel
;;; Extracts prompt box from chat-ui-build-tree.
(in-package :amoebum)

(defun chat-panel-handle-input-key (state key text inner-width)
  (let* ((input-text (chat-ui-state-input-text state))
         (cur-pos (chat-ui-state-cursor-position state))
         (pos (%ensure-cursor-pos input-text cur-pos))
         (input-width (max 1 (- (max 1 inner-width) 2))))
    (cond
      ((eql key :text)
       (if (stringp text)
           (let ((new-text (%grapheme-insert-at input-text pos text))
                 (advance (%grapheme-length text)))
             (chat-ui-set-input state new-text :cursor-position (+ pos advance)))
           (chat-ui-set-input state input-text)))
      ((eql key :ctrl-p)
       (%chat-plan-move-selection! state -1))
      ((eql key :ctrl-n)
       (%chat-plan-move-selection! state 1))
      ((eql key :ctrl-r)
       (if (chat-ui-state-history-search-active-p state)
           (%chat-deactivate-history-search! state :restore-input-p t)
           (%chat-activate-history-search! state)))
      ((eql key :escape)
       (when (chat-ui-state-history-search-active-p state)
         (%chat-deactivate-history-search! state :restore-input-p t))
       t)
      ((eql key :ctrl-j)
       (let ((new-text (%grapheme-insert-at input-text pos (string #\Newline))))
         (chat-ui-set-input state new-text :cursor-position (1+ pos))))
      ((eql key :tab)
       (%handle-command-tab-completion state))
      ((or (eql key :enter) (eql key :return))
       ;; If interactive plan execution is awaiting approval and input is empty,
       ;; approve the next step instead of submitting.
       (if (and (plan-step-awaiting-approval-p)
                (zerop (length input-text)))
           (approve-next-plan-step)
           (if (%handle-slash-command-input state input-text)
               t
               (if (%handle-plan-mode-entry-instruction state input-text)
                   t
                   (let ((submitted (chat-ui-submit-input state)))
                     (when submitted
                       (if (%handle-memory-candidate state submitted)
                           (conversation-transition! (%ensure-chat-conversation-state state)
                                                     :idle)
                           (%start-streaming-assistant-response state submitted)))))))
       t)
      ((eql key :backspace)
       (if (null cur-pos)
           ;; Cursor at end — use fast path
           (chat-ui-set-input state (%pop-last-grapheme input-text))
           ;; Cursor in middle — grapheme-aware delete before
           (multiple-value-bind (new-text new-pos)
               (%grapheme-delete-before input-text pos)
             (chat-ui-set-input state new-text :cursor-position new-pos)))
       t)
      ((eql key :delete)
       ;; Delete grapheme at cursor position (forward delete)
       (chat-ui-set-input state (%grapheme-delete-at input-text pos)
                          :cursor-position pos)
       t)
      ((eql key :ctrl-w)
       ;; Delete word backward from cursor position
       (if (null cur-pos)
           (chat-ui-set-input state (%delete-word-backward input-text))
           (multiple-value-bind (new-text new-pos)
               (%delete-word-backward-at input-text pos)
             (chat-ui-set-input state new-text :cursor-position new-pos)))
       t)
      ((eql key :ctrl-u)
       ;; Kill from start to cursor
       (let* ((clusters (ptui.text.grapheme:split-graphemes input-text))
              (after (with-output-to-string (out)
                       (loop for cluster in (nthcdr pos clusters)
                             do (write-string cluster out)))))
         (chat-ui-set-input state after :cursor-position 0))
       t)
        ((eql key :ctrl-k)
         ;; Kill from cursor to end
         (let* ((clusters (ptui.text.grapheme:split-graphemes input-text))
               (before (with-output-to-string (out)
                        (loop for cluster in (subseq clusters 0 (min pos (length clusters)))
                              do (write-string cluster out)))))
         (chat-ui-set-input state before :cursor-position pos)
         t))
      ((eql key :ctrl-a)
       (setf (chat-ui-state-cursor-position state) 0)
       t)
      ((eql key :ctrl-e)
       (setf (chat-ui-state-cursor-position state) nil)
       t)
      ((eql key :left)
       (when (> pos 0)
         (setf (chat-ui-state-cursor-position state) (1- pos)))
       t)
      ((eql key :right)
       (let ((len (%grapheme-length input-text)))
         (if (< pos len)
             (let ((new-pos (1+ pos)))
               (setf (chat-ui-state-cursor-position state)
                     (if (= new-pos len) nil new-pos)))
             (setf (chat-ui-state-cursor-position state) nil)))
       t)
      ((eql key :ctrl-left)
       (let ((new-pos (%word-boundary-backward input-text pos)))
         (setf (chat-ui-state-cursor-position state) new-pos))
       t)
      ((eql key :ctrl-right)
       (let* ((new-pos (%word-boundary-forward input-text pos))
              (len (%grapheme-length input-text)))
         (setf (chat-ui-state-cursor-position state)
               (if (>= new-pos len) nil new-pos)))
       t)
      ((eql key :home)
       (setf (chat-ui-state-cursor-position state) 0)
       t)
      ((eql key :end)
       (setf (chat-ui-state-cursor-position state) nil)
       t)
      ((eql key :up)
       (let* ((lines (%prompt-wrapped-lines input-text input-width)))
         (multiple-value-bind (cur-line cur-col)
             (%cursor-to-line-col pos lines)
           (when (> cur-line 0)
             (let* ((prev-line (nth (1- cur-line) lines))
                    (target-col (min cur-col (length prev-line)))
                    (new-pos (%line-col-to-cursor-pos (1- cur-line) target-col lines)))
               (setf (chat-ui-state-cursor-position state) new-pos)))))
       t)
      ((eql key :down)
       (let* ((lines (%prompt-wrapped-lines input-text input-width)))
         (multiple-value-bind (cur-line cur-col)
             (%cursor-to-line-col pos lines)
           (when (< cur-line (1- (length lines)))
             (let* ((next-line (nth (1+ cur-line) lines))
                    (target-col (min cur-col (length next-line)))
                    (new-pos (%line-col-to-cursor-pos (1+ cur-line) target-col lines)))
               (setf (chat-ui-state-cursor-position state)
                     (if (and (= (1+ cur-line) (1- (length lines)))
                              (= target-col (length next-line)))
                         nil
                         new-pos))))))
       t)
      (t
       nil))))

(ptui.ui.panel:defpanel prompt-input-panel (chat-state inner-width)
  (:layout
    (:column
      (input :fixed 4
        (ptui.components.prompt-box:make-prompt-box-widget
         (chat-ui-state-input-text chat-state)
         :id :chat-input
         :min-width 18
         :max-width inner-width
         :min-rows 1
         :max-rows 4
         :scroll-offset (chat-ui-state-prompt-scroll-offset chat-state)
         :cursor-position (chat-ui-state-cursor-position chat-state)
         :border-style :rounded))))
  (:keys
    (:text (chat-panel-handle-input-key
             chat-state
             :text
             (ptui.core.events:key-event-text? ptui.ui.panel::event)
             inner-width))
    (:enter (chat-panel-handle-input-key chat-state :enter nil inner-width))
    (:backspace (chat-panel-handle-input-key chat-state :backspace nil inner-width))
    (:delete (chat-panel-handle-input-key chat-state :delete nil inner-width))
    (:ctrl-j (chat-panel-handle-input-key chat-state :ctrl-j nil inner-width))
    (:tab (chat-panel-handle-input-key chat-state :tab nil inner-width))
    (:up (chat-panel-handle-input-key chat-state :up nil inner-width))
    (:down (chat-panel-handle-input-key chat-state :down nil inner-width))
    (:ctrl-p (chat-panel-handle-input-key chat-state :ctrl-p nil inner-width))
    (:ctrl-n (chat-panel-handle-input-key chat-state :ctrl-n nil inner-width))
    (:ctrl-r (chat-panel-handle-input-key chat-state :ctrl-r nil inner-width))
    (:ctrl-a (chat-panel-handle-input-key chat-state :ctrl-a nil inner-width))
    (:ctrl-e (chat-panel-handle-input-key chat-state :ctrl-e nil inner-width))
    (:left (chat-panel-handle-input-key chat-state :left nil inner-width))
    (:right (chat-panel-handle-input-key chat-state :right nil inner-width))
    (:ctrl-left (chat-panel-handle-input-key chat-state :ctrl-left nil inner-width))
    (:ctrl-right (chat-panel-handle-input-key chat-state :ctrl-right nil inner-width))
    (:home (chat-panel-handle-input-key chat-state :home nil inner-width))
    (:end (chat-panel-handle-input-key chat-state :end nil inner-width))
    (:ctrl-w (chat-panel-handle-input-key chat-state :ctrl-w nil inner-width))
    (:ctrl-u (chat-panel-handle-input-key chat-state :ctrl-u nil inner-width))
    (:ctrl-k (chat-panel-handle-input-key chat-state :ctrl-k nil inner-width))))
