(defpackage :amoebum
  (:use :cl)
  (:export #:main
           #:deftool
           #:defhook
           #:defkeys
           #:event
           #:event-p
           #:make-event
           #:event-type
           #:event-seq
           #:event-ts-mono
           #:event-timestamp
           #:event-source
           #:event-severity
           #:event-payload
           #:event-bus
           #:event-bus-p
           #:make-event-bus
           #:current-event-bus
           #:*event-bus*
           #:event-history
           #:subscribe
           #:unsubscribe
           #:publish
           #:+event-type-tool-invoked+
           #:+event-type-tool-completed+
           #:+event-type-tool-error+
           #:+event-type-config-changed+
           #:+event-type-permission-prompted+
           #:+event-type-memory-updated+
           #:+event-type-memory-backend-selected+
           #:+event-type-context-compressed+
           #:+event-type-mcp-tool-discovered+
           #:+event-type-mcp-tool-invoked+
           #:+core-event-types+
           #:tool-invoked-payload
           #:tool-invoked-payload-p
           #:make-tool-invoked-payload
           #:tool-completed-payload
           #:tool-completed-payload-p
           #:make-tool-completed-payload
           #:tool-error-payload
           #:tool-error-payload-p
           #:make-tool-error-payload
           #:config-changed-payload
           #:config-changed-payload-p
           #:make-config-changed-payload
           #:config-changed-payload-key
           #:config-changed-payload-old-value
           #:config-changed-payload-new-value
           #:permission-prompted-payload
           #:permission-prompted-payload-p
           #:make-permission-prompted-payload
           #:memory-updated-payload
           #:memory-updated-payload-p
           #:make-memory-updated-payload
           #:memory-backend-selected-payload
           #:memory-backend-selected-payload-p
           #:make-memory-backend-selected-payload
           #:memory-backend-selected-payload-backend
           #:memory-backend-selected-payload-reason
           #:memory-backend-selected-payload-requested-backend
           #:context-compressed-payload
           #:context-compressed-payload-p
           #:make-context-compressed-payload
           #:mcp-tool-discovered-payload
           #:mcp-tool-discovered-payload-p
           #:make-mcp-tool-discovered-payload
           #:mcp-tool-invoked-payload
           #:mcp-tool-invoked-payload-p
           #:make-mcp-tool-invoked-payload
           #:context-compressed-payload-before-tokens
           #:context-compressed-payload-after-tokens
           #:context-compressed-payload-saved-tokens
           #:context-compressed-payload-summarized-messages
           #:context-compressed-payload-kept-messages
           #:context-compressed-payload-trigger
           #:make-tool-invoked-event
           #:make-tool-completed-event
           #:make-tool-error-event
           #:make-config-changed-event
           #:make-permission-prompted-event
           #:make-memory-updated-event
           #:make-memory-backend-selected-event
           #:make-context-compressed-event
           #:make-mcp-tool-discovered-event
           #:make-mcp-tool-invoked-event
           #:notification
           #:notification-p
           #:make-notification
           #:notification-title
           #:notification-body
           #:notification-severity
           #:notification-category
           #:notification-source-event
           #:notification-timestamp
           #:notification-urgency
           #:notification-timeout-ms
           #:notification-backend
           #:backend-name
           #:backend-enabled-p
           #:backend-config
           #:sound-backend
           #:sound-backend-player-command
           #:sound-backend-sound-map
           #:desktop-backend
           #:desktop-backend-command
           #:desktop-backend-app-name
           #:log-backend
           #:log-backend-path
           #:log-backend-include-event-payload-p
           #:notify-send
           #:notify-available-p
           #:notify-teardown
           #:notification-manager
           #:notification-manager-p
           #:notification-manager-event-bus
           #:notification-manager-backends
           #:notification-manager-enabled-events
           #:notification-manager-subscription-ids
           #:*notification-command-runner*
           #:*notification-command-prober*
           #:*notification-async-dispatch-p*
           #:*notification-manager-registry*
           #:notification-command-available-p
           #:notification-run-command
           #:make-sound-backend
           #:make-desktop-backend
           #:make-log-backend
           #:dispatch-notification
           #:make-notification-manager
           #:ensure-notification-manager
           #:stop-notification-manager
           #:stop-all-notification-managers
           #:*toolset*
           #:*tool-metadata*
           #:tool-metadata
           #:tool-metadata-p
           #:tool-metadata-name
           #:tool-metadata-permission
           #:tool-metadata-dangerous-p
           #:tool-metadata-category
           #:tool-metadata-timeout-seconds
           #:tool-metadata-source-file
           #:tool-metadata-source-line
           #:tool-metadata-parameter-specs
           #:tool-metadata-defined-at
           #:cl-type-to-json-schema
           #:config
           #:config-p
           #:config-model
           #:config-permission-mode
           #:config-memory-backend
           #:config-project-root
           #:config-values
           #:configuration-error
           #:configuration-error-key
           #:configuration-error-value
           #:configuration-error-reason
           #:configure
           #:load-config
           #:reload-config
           #:current-config
           #:config-value
           #:setconfig
           #:emit-config-changed
           #:*current-config*
           #:+default-context-window-limit+
           #:+model-context-window-limits+
           #:+context-budget-green-threshold-percent+
           #:+context-budget-yellow-threshold-percent+
           #:+context-budget-compress-threshold-percent+
           #:*context-window-limit*
           #:context-window-limit-for-model
           #:resolve-context-window-limit
           #:context-usage-percent
           #:context-usage-level
           #:context-compression-required-p
           #:count-tokens
           #:+conversation-states+
           #:+conversation-state-transitions+
           #:invalid-conversation-transition
           #:invalid-conversation-transition-from
           #:invalid-conversation-transition-to
           #:invalid-conversation-transition-allowed
           #:conversation-history-entry
           #:conversation-history-entry-p
           #:make-conversation-history-entry
           #:conversation-history-entry-timestamp
           #:conversation-history-entry-role
           #:conversation-history-entry-content
           #:conversation-history-entry-name
           #:conversation-history-entry-partial
           #:conversation-history-entry-tool-call-id
           #:conversation-state
           #:conversation-state-p
           #:make-conversation-state
           #:conversation-state-session-id
           #:conversation-state-state
           #:conversation-state-entries
           #:conversation-state-created-at
           #:conversation-state-updated-at
           #:conversation-state-project-root
           #:conversation-state-session-path
           #:conversation-message->entry
           #:conversation-entry->message
           #:conversation-session-directory
           #:conversation-session-path
           #:conversation-transition-allowed-p
           #:conversation-transition!
           #:conversation-save
           #:conversation-state-add-message
           #:conversation-state-messages
           #:conversation-load
           #:conversation-load-latest
           #:conversation-load-session
           #:parse-history-timestamp
           #:conversation-search-history
           #:format-history-timestamp
           #:format-history-entry-line
           #:plan-step
           #:plan-step-p
           #:make-plan-step
           #:plan-step-index
           #:plan-step-description
           #:plan-step-file-paths
           #:plan-step-risk
           #:plan-step-depends-on
           #:plan-mode-state
           #:plan-mode-state-p
           #:plan-mode-state-active-p
           #:plan-mode-state-entered-at
           #:plan-mode-state-exited-at
           #:plan-mode-state-steps
           #:plan-mode-state-last-output-path
           #:plan-mode-state-last-exit-reason
           #:*plan-mode-state*
           #:current-plan-mode-state
           #:plan-mode-active-p
           #:clear-plan-mode-steps
           #:add-plan-step
           #:default-plan-output-path
           #:write-plan-output
           #:enter-plan-mode
           #:exit-plan-mode
           #:toggle-plan-mode
           #:+event-type-agent-spawn+
           #:+event-type-agent-complete+
           #:+event-type-agent-cancelled+
           #:agent-cancelled
           #:agent-cancelled-agent-id
           #:agent-record
           #:agent-record-p
           #:agent-record-id
           #:agent-record-type
           #:agent-record-task
           #:agent-record-parent-message-id
           #:agent-record-status
           #:agent-record-created-ms
           #:agent-record-started-ms
           #:agent-record-finished-ms
           #:agent-record-cancel-requested-p
           #:agent-record-result
           #:agent-record-stdout
           #:agent-record-stderr
           #:agent-record-error-message
           #:*agent-registry*
           #:*agent-completion-queue*
           #:clear-agents
           #:find-agent
           #:list-agents
           #:active-agent-count
           #:spawn-agent
           #:cancel-agent
           #:agent-cancel-requested-p
           #:agent-check-cancel
           #:agent-output
           #:drain-agent-completions
           #:memory-backend
           #:file-memory-backend
           #:file-memory-backend-p
           #:make-file-memory-backend
           #:file-memory-backend-global-path
           #:file-memory-backend-project-path
           #:file-memory-backend-project-root
           #:haake-cli-memory-backend
           #:haake-cli-memory-backend-p
           #:make-haake-cli-memory-backend
           #:haake-cli-memory-backend-command
           #:haake-cli-memory-backend-project-id
           #:haake-cli-memory-backend-agent
           #:haake-cli-available-p
           #:haake-cli-status-ok-p
           #:haake-cli-compatible-p
           #:*haake-cli-command-runner*
           #:*haake-cli-availability-runner*
           #:*haake-cli-status-runner*
           #:*haake-cli-capability-runner*
           #:memory-entry
           #:memory-entry-p
           #:make-memory-entry
           #:memory-entry-key
           #:memory-entry-value
           #:memory-entry-scope
           #:memory-entry-source
           #:memory-entry-created-at
           #:memory-candidate
           #:memory-candidate-p
           #:make-memory-candidate
           #:memory-candidate-kind
           #:memory-candidate-text
           #:memory-candidate-key
           #:memory-candidate-confidence
           #:*memory-backend*
           #:*session-memory-entries*
           #:*memory-editor-runner*
           #:reset-memory-backend
           #:current-memory-backend
           #:session-memory-entries
           #:memory-store
           #:memory-query
           #:memory-list
           #:memory-delete
           #:memory-forget
           #:default-memory-editor-runner
           #:memory-command-input-p
           #:memory-command-show
           #:memory-command-edit
           #:memory-command-clear
           #:run-memory-command
           #:extract-durable-memory-candidate
           #:apply-memory-candidate
           #:slash-command-parameter
           #:slash-command-parameter-p
           #:make-slash-command-parameter
           #:slash-command-parameter-name
           #:slash-command-parameter-type
           #:slash-command-parameter-required-p
           #:slash-command-parameter-default
           #:slash-command-parameter-choices
           #:slash-command-parameter-greedy-p
           #:slash-command-parameter-description
           #:slash-command
           #:slash-command-p
           #:make-slash-command
           #:slash-command-name
           #:slash-command-description
           #:slash-command-usage
           #:slash-command-aliases
           #:slash-command-parameters
           #:slash-command-handler
           #:slash-command-completer
           #:slash-command-invocation
           #:slash-command-invocation-p
           #:make-slash-command-invocation
           #:slash-command-invocation-input
           #:slash-command-invocation-name
           #:slash-command-invocation-arguments-text
           #:slash-command-invocation-argument-tokens
           #:slash-command-result
           #:slash-command-result-p
           #:make-slash-command-result
           #:slash-command-result-handledp
           #:slash-command-result-echo-input-p
           #:slash-command-result-output
           #:slash-command-result-action
           #:slash-command-result-payload
           #:slash-command-context
           #:slash-command-context-p
           #:make-slash-command-context
           #:slash-command-context-config
           #:slash-command-context-memory-backend
           #:slash-command-context-chat-state
           #:*slash-command-registry*
           #:slash-command-input-p
           #:parse-slash-command
           #:parse-slash-command-arguments
           #:clear-slash-commands
           #:register-slash-command
           #:find-slash-command
           #:list-slash-commands
           #:complete-slash-command-input
           #:dispatch-slash-command
           #:register-builtin-slash-commands
           #:+hook-point-definitions+
           #:*hook-registry*
           #:register-hook
           #:unregister-hook
           #:list-hooks
           #:clear-hooks
           #:describe-hooks
           #:run-hooks
           #:malformed-key-binding
           #:malformed-key-binding-key-spec
           #:malformed-key-binding-reason
           #:keymap-definition-warning
           #:keymap-definition-warning-keymap
           #:keymap-definition-warning-key-spec
           #:keymap-definition-warning-reason
           #:key-binding
           #:key-binding-p
           #:key-binding-signature
           #:key-binding-handler
           #:key-binding-guard
           #:key-binding-description
           #:key-binding-source-file
           #:key-binding-source-line
           #:key-chord
           #:key-chord-p
           #:key-chord-sequence
           #:key-chord-handler
           #:key-chord-guard
           #:key-chord-description
           #:key-chord-source-file
           #:key-chord-source-line
           #:keymap
           #:keymap-p
           #:make-keymap
           #:keymap-name
           #:keymap-description
           #:keymap-bindings
           #:keymap-chords
           #:*keymap-registry*
           #:*keymap-stack*
           #:*key-sequence-buffer*
           #:register-keymap
           #:list-keymaps
           #:find-keymap
           #:clear-keymaps
           #:register-key-binding
           #:keymap-bindings-list
           #:define-chord
           #:push-keymap
           #:pop-keymap
           #:current-keymap
           #:reset-keymap-stack
           #:dispatch-key-event
           #:dispatch-active-keymaps
           #:make-key-dispatch-on-event
           #:activate-default-keymaps
           #:*chat-mode-keymap*
           #:*command-mode-keymap*
           #:*diff-mode-keymap*
           #:amoebum-error
           #:amoebum-error-message
           #:tool-error
           #:tool-error-tool-name
           #:tool-error-arguments
           #:tool-error-cause
           #:tool-error-reason
           #:tool-execution-error
           #:tool-timeout
           #:tool-timeout-seconds
           #:tool-timeout-error
           #:tool-permission-denied
           #:tool-not-found
           #:tool-not-found-error
           #:tool-argument-error
           #:tool-argument-error-argument-name
           #:tool-missing-argument
           #:tool-type-mismatch
           #:hook-execution-error
           #:hook-execution-error-hook-id
           #:hook-execution-error-hook-point
           #:hook-execution-error-cause
           #:mcp-timeout
           #:mcp-timeout-request-id
           #:mcp-timeout-timeout-seconds
           #:*mcp-jsonrpc-default-timeout-seconds*
           #:mcp-jsonrpc-client
           #:mcp-jsonrpc-client-p
           #:make-mcp-jsonrpc-client
           #:mcp-jsonrpc-client-input-stream
           #:mcp-jsonrpc-client-output-stream
           #:mcp-jsonrpc-client-default-timeout-seconds
           #:mcp-jsonrpc-client-reader-running-p
           #:mcp-jsonrpc-client-reader-error
           #:make-jsonrpc-request-message
           #:make-jsonrpc-notification-message
           #:make-jsonrpc-response-message
           #:jsonrpc-serialize-message
           #:jsonrpc-deserialize-message
           #:jsonrpc-frame-message
           #:jsonrpc-write-message
           #:jsonrpc-read-message
           #:mcp-jsonrpc-send-message
           #:mcp-jsonrpc-send-notification
           #:mcp-jsonrpc-send-request
           #:mcp-jsonrpc-start-reader
           #:mcp-jsonrpc-stop-reader
           #:mcp-jsonrpc-poll
           #:mcp-jsonrpc-handle-incoming-message
           #:mcp-jsonrpc-drain-notifications
           #:*mcp-server-initialize-timeout-seconds*
           #:*mcp-server-ping-timeout-seconds*
           #:*mcp-server-health-check-interval-seconds*
           #:*mcp-server-restart-backoff-base-seconds*
           #:*mcp-server-restart-backoff-max-seconds*
           #:*mcp-server-shutdown-grace-seconds*
           #:mcp-server
           #:mcp-server-p
           #:make-mcp-server
           #:mcp-server-name
           #:mcp-server-command
           #:mcp-server-args
           #:mcp-server-cwd
           #:mcp-server-initialize-timeout-seconds
           #:mcp-server-ping-timeout-seconds
           #:mcp-server-health-check-interval-seconds
           #:mcp-server-restart-backoff-base-seconds
           #:mcp-server-restart-backoff-max-seconds
           #:mcp-server-shutdown-grace-seconds
           #:mcp-server-auto-restart-p
           #:mcp-server-running-p
           #:mcp-server-process
           #:mcp-server-jsonrpc-client
           #:mcp-server-monitor-thread
           #:mcp-server-restart-count
           #:mcp-server-last-error
           #:mcp-server-start
           #:mcp-server-stop
           #:mcp-server-health-check
           #:mcp-server-restart
           #:*mcp-tool-server-registry*
           #:*mcp-tool-binding-registry*
           #:mcp-tool-binding
           #:mcp-tool-binding-p
           #:mcp-tool-binding-server-name
           #:mcp-tool-binding-tool-name
           #:mcp-tool-binding-namespaced-name
           #:mcp-tool-binding-description
           #:mcp-tool-binding-input-schema
           #:mcp-tool-binding-server
           #:clear-mcp-tool-registries
           #:register-mcp-tool-server
           #:unregister-mcp-tool-server
           #:find-mcp-tool-server
           #:discover-mcp-server-tools
           #:invoke-mcp-tool
           #:*lsp-server-initialize-timeout-seconds*
           #:*lsp-request-timeout-seconds*
           #:*lsp-server-restart-backoff-base-seconds*
           #:*lsp-server-restart-backoff-max-seconds*
           #:*lsp-server-shutdown-grace-seconds*
           #:*lsp-default-server-specs*
           #:*lsp-process-spawner*
           #:lsp-server-spec
           #:lsp-server-spec-p
           #:make-lsp-server-spec
           #:lsp-server-spec-name
           #:lsp-server-spec-language-id
           #:lsp-server-spec-command
           #:lsp-server-spec-args
           #:lsp-server-spec-file-extensions
           #:lsp-document-state
           #:lsp-document-state-p
           #:make-lsp-document-state
           #:lsp-document-state-path
           #:lsp-document-state-uri
           #:lsp-document-state-language-id
           #:lsp-document-state-text
           #:lsp-document-state-version
           #:lsp-server-connection
           #:lsp-server-connection-p
           #:lsp-server-connection-spec
           #:lsp-server-connection-process
           #:lsp-server-connection-jsonrpc-client
           #:lsp-server-connection-open-documents
           #:lsp-server-connection-restart-count
           #:lsp-server-connection-last-error
           #:lsp-client
           #:lsp-client-p
           #:make-lsp-client
           #:lsp-client-project-root
           #:lsp-client-server-specs
           #:lsp-client-initialize-timeout-seconds
           #:lsp-client-request-timeout-seconds
           #:lsp-client-restart-backoff-base-seconds
           #:lsp-client-restart-backoff-max-seconds
           #:lsp-client-shutdown-grace-seconds
           #:lsp-client-auto-restart-p
           #:lsp-language-id-for-path
           #:lsp-server-spec-for-path
           #:lsp-client-connection
           #:lsp-client-ensure-server
           #:lsp-open-document
           #:lsp-send-notification
           #:lsp-send-request
           #:lsp-drain-notifications
           #:lsp-client-stop
           #:context-overflow-error
           #:context-overflow-used-tokens
           #:context-overflow-max-tokens
           #:budget-exceeded-error
           #:budget-exceeded-kind
           #:budget-exceeded-used
           #:budget-exceeded-budget
           #:condition-to-llm-context
           #:+tool-restart-names+
           #:*supervised-restart-selector*
           #:default-supervised-restart-selector
           #:execute-tool-with-restarts
           #:tool-execution-context
           #:amoebum-context
           #:make-amoebum-context
           #:context-toolset
           #:context-permission-mode
           #:context-event-bus
           #:context-hook-registry
           #:context-metrics
           #:context-result-cache
           #:context-logger
           #:execute-tool
           #:context-tool-metrics
           #:cached-tool-result
           #:clear-tool-result-cache
           #:clear-tool-metrics
           #:permission-rule
           #:permission-rule-p
           #:permission-rule-effect
           #:permission-rule-path
           #:permission-rule-tool
           #:permission-rule-source
           #:make-permission-rule
           #:*permission-rules*
           #:*dangerous-command-patterns*
           #:clear-permission-rules
           #:add-permission-rule
           #:evaluate-path-permission
           #:dangerous-command-p
           #:check-permission
           #:+system-prompt-base-layer+
           #:resolve-system-prompt-layers
           #:system-prompt-dynamic-context
           #:assemble-system-prompt
           #:+chat-stream-default-system-prompt+
           #:token-stream-cancelled
           #:token-stream-state
           #:token-stream-state-p
           #:make-token-stream-state
           #:token-stream-state-status
           #:token-stream-state-started-ms
           #:token-stream-state-ended-ms
           #:token-stream-state-token-count
           #:token-stream-state-chunk-count
           #:token-stream-state-target-message-index
           #:token-stream-state-cancel-requested-p
           #:token-stream-state-error-message
           #:token-stream-state-worker-thread
           #:token-stream-active-p
           #:token-stream-cancel-requested-p
           #:token-stream-request-cancel
           #:token-stream-check-cancel
           #:token-stream-emit-chunk
           #:token-stream-mark-complete
           #:token-stream-mark-cancelled
           #:token-stream-mark-failed
           #:token-stream-start
           #:token-stream-drain-events
           #:token-stream-elapsed-ms
           #:token-stream-tokens-per-second
           #:token-stream-progress-summary
           #:stream-pseudopod-chat
           #:+event-type-ui-stream-progress+
           #:status-bar-stream-payload
           #:status-bar-stream-payload-p
           #:make-status-bar-stream-payload
           #:status-bar-stream-payload-status
           #:status-bar-stream-payload-activep
           #:status-bar-stream-payload-tokens-used
           #:status-bar-stream-payload-tokens-per-second
           #:status-bar-state
           #:status-bar-state-p
           #:make-status-bar-state
           #:status-bar-state-permission-mode
           #:status-bar-state-plan-mode-active-p
           #:status-bar-state-branch-name
           #:status-bar-state-model-name
           #:status-bar-state-context-used-tokens
           #:status-bar-state-context-max-tokens
           #:status-bar-state-stream-status
           #:status-bar-state-stream-tokens-per-second
           #:status-bar-state-event-bus
           #:status-bar-state-subscription-ids
           #:ensure-status-bar-state
           #:status-bar-subscribe
           #:status-bar-unsubscribe
           #:publish-status-bar-stream-summary
           #:status-bar-segments
           #:status-bar-styled-segments
           #:status-bar-line
           #:status-bar-render-key
           #:make-status-bar-widget
           #:chat-ui-state
           #:chat-ui-state-p
           #:make-chat-ui-state
           #:chat-ui-state-runtime
           #:chat-ui-state-messages
           #:chat-ui-state-input-text
           #:chat-ui-state-message-scrollback-lines
           #:chat-ui-state-max-message-scrollback-lines
           #:chat-ui-state-prompt-scroll-offset
           #:chat-ui-state-stream-state
           #:chat-ui-state-stream-runner
           #:chat-ui-state-stream-client
           #:chat-ui-state-stream-system-prompt
           #:chat-ui-state-stream-tools
           #:chat-ui-state-status-bar-state
           #:chat-ui-state-conversation
           #:chat-ui-state-context-used-tokens
           #:chat-ui-state-context-window-limit
           #:ensure-chat-ui-state
           #:chat-ui-restore-latest-session
           #:make-chat-message
           #:chat-ui-append-message
           #:chat-ui-add-message
           #:chat-ui-set-input
           #:chat-ui-submit-input
           #:chat-ui-scroll-history
           #:chat-role-prefix
           #:chat-role-cell
           #:chat-ui-build-tree
           #:render-chat-ui-buffer
           #:handle-chat-ui-event
           #:run-chat-ui))

(defpackage :amoebum.tools
  (:use :cl))

(defpackage :amoebum.internal
  (:use :cl))
