(defpackage :amoebum
  (:use :cl)
  (:export #:main
           #:deftool
           #:defhook
           #:defkeys
           #:defskill
           #:*skill-registry*
           #:*skill-review-analyzer*
           #:skill-argument
           #:skill-argument-p
           #:make-skill-argument
           #:skill-argument-name
           #:skill-argument-variable
           #:skill-argument-type
           #:skill-argument-required-p
           #:skill-argument-default
           #:skill-argument-default-supplied-p
           #:skill-argument-choices
           #:skill-argument-greedy-p
           #:skill-argument-prompt
           #:skill-argument-description
           #:skill-argument-completer
           #:skill-metadata
           #:skill-metadata-p
           #:make-skill-metadata
           #:skill-metadata-name
           #:skill-metadata-description
           #:skill-metadata-usage
           #:skill-metadata-aliases
           #:skill-metadata-category
           #:skill-metadata-keybinding
           #:skill-metadata-arguments
           #:skill-metadata-handler
           #:skill-metadata-completer
           #:skill-metadata-source-file
           #:skill-metadata-source-line
           #:skill-metadata-defined-at
           #:register-skill
           #:find-skill
           #:list-skills
           #:describe-skill
           #:event
           #:event-p
           #:make-event
           #:event-type
           #:event-seq
           #:event-ts-mono
           #:event-timestamp
           #:event-source
           #:event-severity
           #:event-payload
           #:event-bus
           #:event-bus-p
           #:make-event-bus
           #:current-event-bus
           #:*event-bus*
           #:event-history
           #:subscribe
           #:unsubscribe
           #:publish
           #:filter-by-type
           #:filter-by-severity
           #:filter-by-source
           #:filter-and
           #:filter-or
           #:filter-not
           #:filter-by-tool
           #:filter-by-permission-mode
           #:event-router
           #:+event-type-tool-invoked+
           #:+event-type-tool-completed+
           #:+event-type-tool-error+
           #:+event-type-tool-redefined+
           #:+event-type-config-changed+
           #:+event-type-permission-prompted+
           #:+event-type-memory-updated+
           #:+event-type-memory-backend-selected+
           #:+event-type-context-compressed+
           #:+event-type-mcp-tool-discovered+
           #:+event-type-mcp-tool-invoked+
           #:+event-type-keymap-overlay-enter+
           #:+event-type-keymap-overlay-exit+
           #:+event-type-extension-loaded+
           #:+event-type-extension-error+
           #:+event-type-stream-budget-warning+
           #:+event-type-conversation-forked+
           #:+event-type-tool-call-started+
           #:+event-type-tool-call-argument-complete+
           #:+event-type-session-checkpointed+
           #:+event-type-session-restored+
           #:+core-event-types+
           #:tool-invoked-payload
           #:tool-invoked-payload-p
           #:make-tool-invoked-payload
           #:tool-completed-payload
           #:tool-completed-payload-p
           #:make-tool-completed-payload
           #:tool-error-payload
           #:tool-error-payload-p
           #:make-tool-error-payload
           #:tool-error-payload-tool-name
           #:tool-error-payload-args
           #:tool-error-payload-condition
           #:tool-error-payload-condition-reason-code
           #:tool-error-payload-elapsed-ms
           #:tool-error-payload-request-id
           #:tool-redefined-payload
           #:tool-redefined-payload-p
           #:make-tool-redefined-payload
           #:tool-redefined-payload-tool-name
           #:tool-redefined-payload-old-metadata
           #:tool-redefined-payload-new-metadata
           #:tool-redefined-payload-metadata-diff
           #:config-changed-payload
           #:config-changed-payload-p
           #:make-config-changed-payload
           #:config-changed-payload-key
           #:config-changed-payload-old-value
           #:config-changed-payload-new-value
           #:permission-prompted-payload
           #:permission-prompted-payload-p
           #:make-permission-prompted-payload
           #:permission-prompted-payload-tool-name
           #:permission-prompted-payload-path
           #:permission-prompted-payload-command
           #:permission-prompted-payload-reason
           #:permission-prompted-payload-reason-code
           #:permission-prompted-payload-permission-mode
           #:memory-updated-payload
           #:memory-updated-payload-p
           #:make-memory-updated-payload
           #:memory-backend-selected-payload
           #:memory-backend-selected-payload-p
           #:make-memory-backend-selected-payload
           #:memory-backend-selected-payload-backend
           #:memory-backend-selected-payload-reason
           #:memory-backend-selected-payload-requested-backend
           #:context-compressed-payload
           #:context-compressed-payload-p
           #:make-context-compressed-payload
           #:mcp-tool-discovered-payload
           #:mcp-tool-discovered-payload-p
           #:make-mcp-tool-discovered-payload
           #:mcp-tool-invoked-payload
           #:mcp-tool-invoked-payload-p
           #:make-mcp-tool-invoked-payload
           #:extension-loaded-payload
           #:extension-loaded-payload-p
           #:make-extension-loaded-payload
           #:extension-loaded-payload-path
           #:extension-loaded-payload-scope
           #:extension-error-payload
           #:extension-error-payload-p
           #:make-extension-error-payload
           #:extension-error-payload-path
           #:extension-error-payload-scope
           #:extension-error-payload-condition
           #:stream-budget-warning-payload
           #:stream-budget-warning-payload-p
           #:make-stream-budget-warning-payload
           #:stream-budget-warning-payload-used-tokens
           #:stream-budget-warning-payload-limit-tokens
           #:stream-budget-warning-payload-usage-percent
           #:stream-budget-warning-payload-threshold-percent
           #:tool-call-started-payload
           #:tool-call-started-payload-p
           #:make-tool-call-started-payload
           #:tool-call-started-payload-tool-name
           #:tool-call-started-payload-tool-call-id
           #:tool-call-started-payload-arguments
           #:tool-call-started-payload-index
           #:tool-call-argument-complete-payload
           #:tool-call-argument-complete-payload-p
           #:make-tool-call-argument-complete-payload
           #:tool-call-argument-complete-payload-tool-name
           #:tool-call-argument-complete-payload-tool-call-id
           #:tool-call-argument-complete-payload-arguments
           #:tool-call-argument-complete-payload-index
           #:session-checkpointed-payload
           #:session-checkpointed-payload-p
           #:make-session-checkpointed-payload
           #:session-checkpointed-payload-checkpoint-id
           #:session-checkpointed-payload-path
           #:session-checkpointed-payload-trigger
           #:session-checkpointed-payload-auto-p
           #:session-checkpointed-payload-message-count
           #:session-checkpointed-payload-extension-count
           #:session-checkpointed-payload-tool-count
           #:session-checkpointed-payload-memory-count
           #:session-restored-payload
           #:session-restored-payload-p
           #:make-session-restored-payload
           #:session-restored-payload-checkpoint-id
           #:session-restored-payload-path
           #:session-restored-payload-trigger
           #:session-restored-payload-message-count
           #:session-restored-payload-extension-count
           #:session-restored-payload-tool-count
           #:session-restored-payload-memory-count
           #:context-compressed-payload-before-tokens
           #:context-compressed-payload-after-tokens
           #:context-compressed-payload-saved-tokens
           #:context-compressed-payload-summarized-messages
           #:context-compressed-payload-kept-messages
           #:context-compressed-payload-trigger
           #:make-tool-invoked-event
           #:make-tool-completed-event
           #:make-tool-error-event
           #:make-tool-redefined-event
           #:make-config-changed-event
           #:make-permission-prompted-event
           #:make-memory-updated-event
           #:make-memory-backend-selected-event
           #:make-context-compressed-event
           #:make-mcp-tool-discovered-event
           #:make-mcp-tool-invoked-event
           #:make-extension-loaded-event
           #:make-extension-error-event
           #:make-stream-budget-warning-event
           #:make-tool-call-started-event
           #:make-tool-call-argument-complete-event
           #:make-session-checkpointed-event
           #:make-session-restored-event
           #:sound-theme
           #:sound-theme-p
           #:make-sound-theme
           #:sound-theme-name
           #:sound-theme-parent
           #:sound-theme-mappings
           #:*sound-theme-registry*
           #:*active-sound-theme*
           #:register-sound-theme
           #:clear-sound-themes
           #:find-sound-theme
           #:list-sound-themes
           #:list-sound-theme-names
           #:active-sound-theme
           #:active-sound-theme-name
           #:set-active-sound-theme
           #:resolve-sound
           #:resolve-sound-path
           #:resolve-active-sound-path
           #:defsoundtheme
           #:defsound-theme
           #:notification
           #:notification-p
           #:make-notification
           #:notification-title
           #:notification-body
           #:notification-severity
           #:notification-category
           #:notification-source-event
           #:notification-timestamp
           #:notification-urgency
           #:notification-timeout-ms
           #:notification-backend
           #:backend-name
           #:backend-enabled-p
           #:backend-config
           #:sound-backend
           #:sound-backend-player-command
           #:sound-backend-sound-map
           #:sound-backend-theme
           #:desktop-backend
           #:desktop-backend-command
           #:desktop-backend-app-name
           #:log-backend
           #:log-backend-path
           #:log-backend-include-event-payload-p
           #:notify-send
           #:notify-available-p
           #:notify-teardown
           #:notification-manager
           #:notification-manager-p
           #:notification-manager-event-bus
           #:notification-manager-backends
           #:notification-manager-enabled-events
           #:notification-manager-subscription-ids
           #:*notification-command-runner*
           #:*notification-command-prober*
           #:*notification-async-dispatch-p*
           #:*notification-manager-registry*
           #:notification-command-available-p
           #:notification-run-command
           #:make-sound-backend
           #:make-desktop-backend
           #:make-log-backend
           #:preview-notification-sound
           #:dispatch-notification
           #:make-notification-manager
           #:ensure-notification-manager
           #:stop-notification-manager
           #:stop-all-notification-managers
           #:*toolset*
           #:*tool-metadata*
           #:*tool-history*
           #:*tool-history-max-versions*
           #:tool-metadata
           #:tool-metadata-p
           #:tool-metadata-name
           #:tool-metadata-permission
           #:tool-metadata-dangerous-p
           #:tool-metadata-category
           #:tool-metadata-timeout-seconds
           #:tool-metadata-source-file
           #:tool-metadata-source-line
           #:tool-metadata-parameter-specs
           #:tool-metadata-defined-at
           #:tool-history-entry
           #:tool-history-entry-p
           #:make-tool-history-entry
           #:tool-history-entry-tool-definition
           #:tool-history-entry-tool-metadata
           #:tool-history-entry-timestamp
           #:tool-history-entry-source-file
           #:tool-history-entry-source-line
           #:tool-history
           #:rollback-tool
           #:cl-type-to-json-schema
           #:config
           #:config-p
           #:config-model
           #:config-permission-mode
           #:*known-sandbox-policies*
           #:config-memory-backend
           #:config-project-root
           #:config-values
           #:configuration-error
           #:configuration-error-key
           #:configuration-error-value
           #:configuration-error-reason
           #:configure
           #:load-config
           #:reload-config
           #:current-config
           #:config-value
           #:config-layer-source
           #:setconfig
           #:resolve-provider
           #:clear-resolved-provider-cache
           #:emit-config-changed
           #:*current-config*
           #:+amoebum-readtable-name+
           #:activate-amoebum-readtable
           #:reader-project-root
           #:resolve-reader-path
           #:glob-paths
           #:compile-reader-regex
           #:malformed-regex
           #:malformed-regex-pattern
           #:malformed-regex-reason
           #:+default-context-window-limit+
           #:+model-context-window-limits+
           #:+context-budget-green-threshold-percent+
           #:+context-budget-yellow-threshold-percent+
           #:+context-budget-compress-threshold-percent+
           #:*context-window-limit*
           #:context-window-limit-for-model
           #:resolve-context-window-limit
           #:context-usage-percent
           #:context-usage-level
           #:context-compression-required-p
           #:count-tokens
           #:+conversation-states+
           #:+conversation-state-transitions+
           #:invalid-conversation-transition
           #:invalid-conversation-transition-from
           #:invalid-conversation-transition-to
           #:invalid-conversation-transition-allowed
           #:conversation-history-entry
           #:conversation-history-entry-p
           #:make-conversation-history-entry
           #:conversation-history-entry-timestamp
           #:conversation-history-entry-role
           #:conversation-history-entry-content
           #:conversation-history-entry-name
           #:conversation-history-entry-partial
           #:conversation-history-entry-tool-call-id
           #:conversation-history-search-result
           #:conversation-history-search-result-p
           #:make-conversation-history-search-result
           #:conversation-history-search-result-index
           #:conversation-history-search-result-score
           #:conversation-history-search-result-entry
           #:conversation-history-search-result-before
           #:conversation-history-search-result-after
           #:conversation-state
           #:conversation-state-p
           #:make-conversation-state
           #:conversation-state-session-id
           #:conversation-state-state
           #:conversation-state-entries
           #:conversation-state-created-at
           #:conversation-state-updated-at
           #:conversation-state-active-fork
           #:conversation-state-fork-branch-point
           #:conversation-state-forks
           #:conversation-state-project-root
           #:conversation-state-session-path
           #:conversation-message->entry
           #:conversation-entry->message
           #:conversation-session-directory
           #:conversation-session-path
           #:conversation-fork-directory
           #:conversation-fork-path
           #:conversation-active-fork-name
           #:conversation-list-forks
           #:conversation-transition-allowed-p
           #:conversation-transition!
           #:conversation-reset!
           #:conversation-save
           #:fork-conversation
           #:conversation-switch-fork
           #:conversation-state-add-message
           #:conversation-state-messages
           #:conversation-load
           #:conversation-load-latest
           #:conversation-load-session
           #:parse-history-timestamp
           #:history-search
           #:conversation-search-history
           #:format-history-timestamp
           #:format-history-entry-line
           #:plan-step
           #:plan-step-p
           #:make-plan-step
           #:plan-step-index
           #:plan-step-description
           #:plan-step-file-paths
           #:plan-step-risk
           #:plan-step-depends-on
           #:plan-mode-state
           #:plan-mode-state-p
           #:plan-mode-state-active-p
           #:plan-mode-state-entered-at
           #:plan-mode-state-exited-at
           #:plan-mode-state-steps
           #:plan-mode-state-last-output-path
           #:plan-mode-state-last-exit-reason
           #:*plan-mode-state*
           #:current-plan-mode-state
           #:plan-mode-active-p
           #:clear-plan-mode-steps
           #:add-plan-step
           #:default-plan-output-path
           #:write-plan-output
           #:enter-plan-mode
           #:exit-plan-mode
           #:toggle-plan-mode
           #:+event-type-agent-spawn+
           #:+event-type-agent-complete+
           #:+event-type-agent-cancelled+
           #:agent-cancelled
           #:agent-cancelled-agent-id
           #:agent-record
           #:agent-record-p
           #:agent-record-id
           #:agent-record-type
           #:agent-record-task
           #:agent-record-parent-message-id
           #:agent-record-status
           #:agent-record-created-ms
           #:agent-record-started-ms
           #:agent-record-finished-ms
           #:agent-record-cancel-requested-p
           #:agent-record-result
           #:agent-record-stdout
           #:agent-record-stderr
           #:agent-record-error-message
           #:*agent-registry*
           #:*agent-completion-queue*
           #:clear-agents
           #:find-agent
           #:list-agents
           #:active-agent-count
           #:spawn-agent
           #:cancel-agent
           #:agent-cancel-requested-p
           #:agent-check-cancel
           #:agent-output
           #:drain-agent-completions
           #:memory-backend
           #:file-memory-backend
           #:file-memory-backend-p
           #:make-file-memory-backend
           #:file-memory-backend-global-path
           #:file-memory-backend-project-path
           #:file-memory-backend-project-root
           #:haake-cli-memory-backend
           #:haake-cli-memory-backend-p
           #:make-haake-cli-memory-backend
           #:haake-cli-memory-backend-command
           #:haake-cli-memory-backend-project-id
           #:haake-cli-memory-backend-agent
           #:haake-cli-available-p
           #:haake-cli-status-ok-p
           #:haake-cli-compatible-p
           #:*haake-cli-command-runner*
           #:*haake-cli-availability-runner*
           #:*haake-cli-status-runner*
           #:*haake-cli-capability-runner*
           #:memory-entry
           #:memory-entry-p
           #:make-memory-entry
           #:memory-entry-key
           #:memory-entry-value
           #:memory-entry-scope
           #:memory-entry-source
           #:memory-entry-created-at
           #:memory-candidate
           #:memory-candidate-p
           #:make-memory-candidate
           #:memory-candidate-kind
           #:memory-candidate-text
           #:memory-candidate-key
           #:memory-candidate-confidence
           #:*memory-backend*
           #:*session-memory-entries*
           #:*memory-editor-runner*
           #:reset-memory-backend
           #:current-memory-backend
           #:session-memory-entries
           #:memory-store
           #:memory-query
           #:memory-list
           #:memory-delete
           #:memory-forget
           #:default-memory-editor-runner
           #:memory-command-input-p
           #:memory-command-show
           #:memory-command-edit
           #:memory-command-clear
           #:run-memory-command
           #:extract-durable-memory-candidate
           #:apply-memory-candidate
           #:extension-load-record
           #:extension-load-record-p
           #:make-extension-load-record
           #:extension-load-record-path
           #:extension-load-record-scope
           #:extension-load-record-status
           #:extension-load-record-message
           #:extension-load-record-timestamp
           #:*extension-load-report*
           #:*loaded-extensions*
           #:*disabled-extensions*
           #:*extensions-global-directory-override*
           #:*extensions-project-directory-override*
           #:discover-user-extension-files
           #:extension-disabled-p
           #:list-extension-report
           #:list-loaded-extensions
           #:extension-report-summary
           #:known-user-extension-paths
           #:disable-user-extension
           #:load-user-extensions
           #:reload-user-extensions
           #:session-checkpoint
           #:session-checkpoint-p
           #:make-session-checkpoint
           #:session-checkpoint-id
           #:session-checkpoint-path
           #:session-checkpoint-created-at
           #:session-checkpoint-auto-p
           #:session-checkpoint-trigger
           #:*checkpoint-directory-override*
           #:*checkpoint-last-activity-at*
           #:*checkpoint-last-auto-checkpoint-at*
           #:checkpoint-directory
           #:list-session-checkpoints
           #:checkpoint-session
           #:restore-session
           #:checkpoint-auto-idle-seconds
           #:checkpoint-mark-activity
           #:maybe-auto-checkpoint
           #:slash-command-parameter
           #:slash-command-parameter-p
           #:make-slash-command-parameter
           #:slash-command-parameter-name
           #:slash-command-parameter-type
           #:slash-command-parameter-required-p
           #:slash-command-parameter-default
           #:slash-command-parameter-choices
           #:slash-command-parameter-greedy-p
           #:slash-command-parameter-description
           #:slash-command
           #:slash-command-p
           #:make-slash-command
           #:slash-command-name
           #:slash-command-description
           #:slash-command-usage
           #:slash-command-aliases
           #:slash-command-parameters
           #:slash-command-handler
           #:slash-command-completer
           #:slash-command-invocation
           #:slash-command-invocation-p
           #:make-slash-command-invocation
           #:slash-command-invocation-input
           #:slash-command-invocation-name
           #:slash-command-invocation-arguments-text
           #:slash-command-invocation-argument-tokens
           #:slash-command-result
           #:slash-command-result-p
           #:make-slash-command-result
           #:slash-command-result-handledp
           #:slash-command-result-echo-input-p
           #:slash-command-result-output
           #:slash-command-result-action
           #:slash-command-result-payload
           #:slash-command-context
           #:slash-command-context-p
           #:make-slash-command-context
           #:slash-command-context-config
           #:slash-command-context-memory-backend
           #:slash-command-context-chat-state
           #:*slash-command-registry*
           #:slash-command-input-p
           #:parse-slash-command
           #:parse-slash-command-arguments
           #:clear-slash-commands
           #:register-slash-command
           #:find-slash-command
           #:list-slash-commands
           #:complete-slash-command-input
           #:dispatch-slash-command
           #:register-builtin-slash-commands
           #:+hook-point-definitions+
           #:*hook-registry*
           #:register-hook
           #:unregister-hook
           #:list-hooks
           #:clear-hooks
           #:describe-hooks
           #:hook-metrics
           #:hook-trace
           #:clear-hook-trace
           #:run-hooks
           #:malformed-key-binding
           #:malformed-key-binding-key-spec
           #:malformed-key-binding-reason
           #:keymap-definition-warning
           #:keymap-definition-warning-keymap
           #:keymap-definition-warning-key-spec
           #:keymap-definition-warning-reason
           #:key-binding
           #:key-binding-p
           #:key-binding-signature
           #:key-binding-handler
           #:key-binding-guard
           #:key-binding-description
           #:key-binding-source-file
           #:key-binding-source-line
           #:key-chord
           #:key-chord-p
           #:key-chord-sequence
           #:key-chord-handler
           #:key-chord-guard
           #:key-chord-description
           #:key-chord-source-file
           #:key-chord-source-line
           #:keymap
           #:keymap-p
           #:keymap-overlay
           #:keymap-overlay-p
           #:keymap-overlay-keymap
           #:keymap-overlay-auto-cleanup-on-escape-p
           #:keymap-overlay-entered-at
           #:make-keymap
           #:keymap-name
           #:keymap-description
           #:keymap-bindings
           #:keymap-chords
           #:*keymap-registry*
           #:*keymap-stack*
           #:*keymap-overlay-stack*
           #:*key-sequence-buffer*
           #:*key-sequence-timeout-ms*
           #:*key-disambiguation-timeout-ms*
           #:*terminal-key-normalization-profile*
           #:*terminal-key-normalization-table*
           #:register-keymap
           #:list-keymaps
           #:find-keymap
           #:clear-keymaps
           #:register-key-binding
           #:keymap-bindings-list
           #:define-chord
           #:push-keymap
           #:pop-keymap
           #:current-keymap
           #:current-keymap-overlay
           #:push-keymap-overlay
           #:pop-keymap-overlay
           #:clear-keymap-overlays
           #:reset-keymap-stack
           #:dispatch-key-event
           #:dispatch-active-keymaps
           #:flush-key-dispatch-timeouts
           #:resolve-terminal-key-normalization-profile
           #:make-key-dispatch-on-event
           #:activate-default-keymaps
           #:*chat-mode-keymap*
           #:*command-mode-keymap*
           #:*diff-mode-keymap*
           #:amoebum-error
           #:amoebum-error-message
           #:tool-error
           #:tool-error-tool-name
           #:tool-error-arguments
           #:tool-error-cause
           #:tool-error-reason
           #:tool-error-reason-code
           #:tool-execution-error
           #:tool-timeout
           #:tool-timeout-seconds
           #:tool-timeout-error
           #:tool-permission-denied
           #:tool-not-found
           #:tool-not-found-error
           #:tool-argument-error
           #:tool-argument-error-argument-name
           #:tool-missing-argument
           #:tool-type-mismatch
           #:hook-execution-error
           #:hook-execution-error-hook-id
           #:hook-execution-error-hook-point
           #:hook-execution-error-cause
           #:mcp-timeout
           #:mcp-timeout-request-id
           #:mcp-timeout-timeout-seconds
           #:*mcp-jsonrpc-default-timeout-seconds*
           #:mcp-jsonrpc-client
           #:mcp-jsonrpc-client-p
           #:make-mcp-jsonrpc-client
           #:mcp-jsonrpc-client-input-stream
           #:mcp-jsonrpc-client-output-stream
           #:mcp-jsonrpc-client-default-timeout-seconds
           #:mcp-jsonrpc-client-reader-running-p
           #:mcp-jsonrpc-client-reader-error
           #:make-jsonrpc-request-message
           #:make-jsonrpc-notification-message
           #:make-jsonrpc-response-message
           #:jsonrpc-serialize-message
           #:jsonrpc-deserialize-message
           #:jsonrpc-frame-message
           #:jsonrpc-write-message
           #:jsonrpc-read-message
           #:mcp-jsonrpc-send-message
           #:mcp-jsonrpc-send-notification
           #:mcp-jsonrpc-send-request
           #:mcp-jsonrpc-start-reader
           #:mcp-jsonrpc-stop-reader
           #:mcp-jsonrpc-poll
           #:mcp-jsonrpc-handle-incoming-message
           #:mcp-jsonrpc-drain-notifications
           #:*mcp-server-initialize-timeout-seconds*
           #:*mcp-server-ping-timeout-seconds*
           #:*mcp-server-health-check-interval-seconds*
           #:*mcp-server-restart-backoff-base-seconds*
           #:*mcp-server-restart-backoff-max-seconds*
           #:*mcp-server-shutdown-grace-seconds*
           #:mcp-server
           #:mcp-server-p
           #:make-mcp-server
           #:mcp-server-name
           #:mcp-server-transport
           #:mcp-server-command
           #:mcp-server-args
           #:mcp-server-cwd
           #:mcp-server-endpoint-url
           #:mcp-server-http-headers
           #:mcp-server-initialize-timeout-seconds
           #:mcp-server-ping-timeout-seconds
           #:mcp-server-health-check-interval-seconds
           #:mcp-server-restart-backoff-base-seconds
           #:mcp-server-restart-backoff-max-seconds
           #:mcp-server-shutdown-grace-seconds
           #:mcp-server-auto-restart-p
           #:mcp-server-running-p
           #:mcp-server-process
           #:mcp-server-jsonrpc-client
           #:mcp-server-monitor-thread
           #:mcp-server-restart-count
           #:mcp-server-last-error
           #:mcp-server-start
           #:mcp-server-stop
           #:mcp-server-health-check
           #:mcp-server-restart
           #:*mcp-tool-server-registry*
           #:*mcp-tool-binding-registry*
           #:mcp-tool-binding
           #:mcp-tool-binding-p
           #:mcp-tool-binding-server-name
           #:mcp-tool-binding-tool-name
           #:mcp-tool-binding-namespaced-name
           #:mcp-tool-binding-description
           #:mcp-tool-binding-input-schema
           #:mcp-tool-binding-server
           #:clear-mcp-tool-registries
           #:register-mcp-tool-server
           #:unregister-mcp-tool-server
           #:find-mcp-tool-server
           #:discover-mcp-server-tools
           #:invoke-mcp-tool
           #:*lsp-server-initialize-timeout-seconds*
           #:*lsp-request-timeout-seconds*
           #:*lsp-server-restart-backoff-base-seconds*
           #:*lsp-server-restart-backoff-max-seconds*
           #:*lsp-server-shutdown-grace-seconds*
           #:*lsp-default-server-specs*
           #:*lsp-process-spawner*
           #:lsp-server-spec
           #:lsp-server-spec-p
           #:make-lsp-server-spec
           #:lsp-server-spec-name
           #:lsp-server-spec-language-id
           #:lsp-server-spec-command
           #:lsp-server-spec-args
           #:lsp-server-spec-file-extensions
           #:lsp-document-state
           #:lsp-document-state-p
           #:make-lsp-document-state
           #:lsp-document-state-path
           #:lsp-document-state-uri
           #:lsp-document-state-language-id
           #:lsp-document-state-text
           #:lsp-document-state-version
           #:lsp-server-connection
           #:lsp-server-connection-p
           #:lsp-server-connection-spec
           #:lsp-server-connection-process
           #:lsp-server-connection-jsonrpc-client
           #:lsp-server-connection-open-documents
           #:lsp-server-connection-restart-count
           #:lsp-server-connection-last-error
           #:lsp-client
           #:lsp-client-p
           #:make-lsp-client
           #:lsp-client-project-root
           #:lsp-client-server-specs
           #:lsp-client-initialize-timeout-seconds
           #:lsp-client-request-timeout-seconds
           #:lsp-client-restart-backoff-base-seconds
           #:lsp-client-restart-backoff-max-seconds
           #:lsp-client-shutdown-grace-seconds
           #:lsp-client-auto-restart-p
           #:lsp-language-id-for-path
           #:lsp-server-spec-for-path
           #:lsp-client-connection
           #:lsp-client-ensure-server
           #:lsp-open-document
           #:lsp-send-notification
           #:lsp-send-request
           #:lsp-request-document-symbols
           #:lsp-request-workspace-symbols
           #:lsp-drain-notifications
           #:lsp-client-stop
           #:context-overflow-error
           #:context-overflow-used-tokens
           #:context-overflow-max-tokens
           #:budget-exceeded-error
           #:budget-exceeded-kind
           #:budget-exceeded-used
           #:budget-exceeded-budget
           #:condition-to-llm-context
           #:+tool-restart-names+
           #:*supervised-restart-selector*
           #:default-supervised-restart-selector
           #:execute-tool-with-restarts
           #:tool-execution-context
           #:amoebum-context
           #:make-amoebum-context
           #:context-toolset
           #:context-permission-mode
           #:context-event-bus
           #:context-hook-registry
           #:context-metrics
           #:context-result-cache
           #:context-logger
           #:execute-tool
           #:context-tool-metrics
           #:cached-tool-result
           #:clear-tool-result-cache
           #:clear-tool-metrics
           #:permission-rule
           #:permission-rule-p
           #:permission-rule-id
           #:permission-rule-effect
           #:permission-rule-path
           #:permission-rule-command
           #:permission-rule-tool
           #:permission-rule-command
           #:permission-rule-arguments
           #:permission-rule-source
           #:make-permission-rule
           #:command-canonical-form
           #:command-canonical-form-p
           #:make-command-canonical-form
           #:command-canonical-form-raw
           #:command-canonical-form-normalized
           #:command-canonical-form-policy-key
           #:command-canonical-form-executable
           #:command-canonical-form-argv
           #:command-canonical-form-operators
           #:command-canonical-form-wrappers
           #:command-canonical-form-commands
           #:command-canonical-form-ast
           #:command-canonical-form-operator-metadata
           #:command-canonical-form-canonical-signature
           #:command-canonical-form-dangerous-reason-codes
           #:path-approval-entry
           #:path-approval-entry-p
           #:make-path-approval-entry
           #:path-approval-entry-tool
           #:path-approval-entry-path
           #:path-approval-entry-scope
           #:path-approval-entry-created-at
           #:path-approval-entry-uses-remaining
           #:*permission-rules*
           #:*path-approval-memory*
           #:*path-approval-memory-limit*
           #:*path-approval-persistence-relative-path*
           #:*dangerous-command-patterns*
           #:clear-permission-rules
           #:clear-permission-cache
           #:permission-cache-metrics
           #:permission-cache-invalidation-events
           #:add-permission-rule
           #:canonicalize-permission-command
           #:command-canonicalization-trace
           #:normalize-permission-path
           #:evaluate-path-permission
           #:evaluate-command-permission
           #:path-approval-store-path
           #:load-path-approvals
           #:save-path-approvals
           #:clear-path-approvals
           #:list-path-approvals
           #:remember-path-approval
           #:forget-path-approval
           #:dangerous-command-p
           #:check-permission
           #:last-permission-decision-trace
           #:permission-decision-history
           #:clear-permission-decision-history
           #:explain-permission-decision
           #:+sandbox-max-output-size+
           #:+sandbox-max-read-size+
           #:sandbox-violation
           #:sandbox-violation-operation
           #:sandbox-violation-reason
           #:sandbox-violation-details
           #:sandbox-read-eval-disabled
           #:sandbox-read-eval-disabled-form
           #:sandbox-read-size-exceeded
           #:sandbox-read-size-exceeded-path
           #:sandbox-read-size-exceeded-size-bytes
           #:sandbox-read-size-exceeded-limit-bytes
           #:normalize-sandbox-policy
           #:sandbox-policy
           #:sandbox-policy-enabled-p
           #:sandbox-check-tool-call
           #:safe-open
           #:safe-run-program
           #:truncate-sandbox-output
           #:apply-sandbox-output-guard
           #:make-restricted-readtable
           #:*sandbox-restricted-readtable*
           #:sandbox-read-from-string
           #:+system-prompt-base-layer+
           #:resolve-system-prompt-layers
           #:system-prompt-dynamic-context
           #:assemble-system-prompt
           #:+chat-stream-default-system-prompt+
           #:+stream-cursor-glyph+
           #:+stream-cursor-blink-ms+
           #:+stream-budget-warning-threshold-percent+
           #:token-stream-cancelled
           #:token-stream-state
           #:token-stream-state-p
           #:make-token-stream-state
           #:token-stream-state-status
           #:token-stream-state-started-ms
           #:token-stream-state-ended-ms
           #:token-stream-state-token-count
           #:token-stream-state-chunk-count
           #:token-stream-state-target-message-index
           #:token-stream-state-cancel-requested-p
           #:token-stream-state-error-message
           #:token-stream-state-budget-warning-threshold-percent
           #:token-stream-state-budget-warning-emitted-p
           #:token-stream-state-worker-thread
           #:token-stream-active-p
           #:token-stream-cancel-requested-p
           #:token-stream-request-cancel
           #:token-stream-check-cancel
           #:token-stream-set-budget-warning-threshold
           #:token-stream-maybe-budget-warning
           #:token-stream-emit-chunk
           #:token-stream-emit-tool-call-delta
           #:token-stream-emit-tool-call-started
           #:token-stream-emit-tool-call-argument-complete
           #:token-stream-mark-complete
           #:token-stream-mark-cancelled
           #:token-stream-mark-failed
           #:token-stream-start
           #:token-stream-drain-events
           #:token-stream-elapsed-ms
           #:token-stream-tokens-per-second
           #:token-stream-progress-summary
           #:stream-cursor-visible-p
           #:stream-markdown-styled-lines
           #:stream-pseudopod-chat
           #:+event-type-ui-stream-progress+
           #:status-bar-stream-payload
           #:status-bar-stream-payload-p
           #:make-status-bar-stream-payload
           #:status-bar-stream-payload-status
           #:status-bar-stream-payload-activep
           #:status-bar-stream-payload-tokens-used
           #:status-bar-stream-payload-tokens-per-second
           #:status-bar-state
           #:status-bar-state-p
           #:make-status-bar-state
           #:status-bar-state-permission-mode
           #:status-bar-state-plan-mode-active-p
           #:status-bar-state-branch-name
           #:status-bar-state-model-name
           #:status-bar-state-context-used-tokens
           #:status-bar-state-context-max-tokens
           #:status-bar-state-stream-status
           #:status-bar-state-stream-tokens-per-second
           #:status-bar-state-event-bus
           #:status-bar-state-subscription-ids
           #:ensure-status-bar-state
           #:status-bar-subscribe
           #:status-bar-unsubscribe
           #:publish-status-bar-stream-summary
           #:status-bar-segments
           #:status-bar-styled-segments
           #:status-bar-line
           #:status-bar-render-key
           #:make-status-bar-widget
           #:chat-ui-state
           #:chat-ui-state-p
           #:make-chat-ui-state
           #:chat-ui-state-runtime
           #:chat-ui-state-messages
           #:chat-ui-state-input-text
           #:chat-ui-state-message-scrollback-lines
           #:chat-ui-state-max-message-scrollback-lines
           #:chat-ui-state-prompt-scroll-offset
           #:chat-ui-state-stream-state
           #:chat-ui-state-stream-runner
           #:chat-ui-state-stream-client
           #:chat-ui-state-stream-system-prompt
           #:chat-ui-state-stream-tools
           #:chat-ui-state-stream-scroll-follow-p
           #:chat-ui-state-status-bar-state
           #:chat-ui-state-conversation
           #:chat-ui-state-context-used-tokens
           #:chat-ui-state-context-window-limit
           #:chat-ui-state-stream-tool-calls
           #:chat-ui-state-stream-executed-tool-call-keys
           #:ensure-chat-ui-state
           #:chat-ui-restore-latest-session
           #:make-chat-message
           #:chat-ui-append-message
           #:chat-ui-add-message
           #:chat-ui-set-input
           #:chat-ui-submit-input
           #:chat-ui-scroll-history
           #:chat-role-prefix
           #:chat-role-cell
           #:chat-ui-build-tree
           #:render-chat-ui-buffer
           #:handle-chat-ui-event
           #:run-chat-ui
           ;; Phase 5 (I94-I102)
           #:*model-router*
           ;; Indexer (I96)
           #:symbol-entry
           #:symbol-entry-p
           #:make-symbol-entry
           #:symbol-entry-name
           #:symbol-entry-package
           #:symbol-entry-kind
           #:symbol-entry-file
           #:symbol-entry-line
           #:symbol-entry-signature
           #:symbol-entry-doc
           #:codebase-index
           #:codebase-index-p
           #:make-codebase-index
           #:codebase-index-entries
           #:codebase-index-file-mtimes
           #:codebase-index-created-at
           #:codebase-index-updated-at
           #:index-package-symbols
           #:index-directory
           #:generate-repo-map
           #:index-find-symbol
           #:index-find-by-file
           #:index-statistics
           ;; Self-modify (I98)
           #:+event-type-self-modify-proposed+
           #:+event-type-self-modify-approved+
           #:+event-type-self-modify-applied+
           #:+event-type-self-modify-rolled-back+
           #:modification-entry
           #:modification-entry-p
           #:make-modification-entry
           #:modification-entry-id
           #:modification-entry-form-text
           #:modification-entry-result
           #:modification-entry-status
           #:modification-entry-timestamp
           #:modification-entry-applied-symbols
           #:modification-entry-error-message
           #:*modification-journal*
           #:modification-journal
           #:clear-modification-journal
           #:find-modification
           #:sandboxed-eval
           #:*self-modify-auto-approve-p*
           #:propose-modification
           #:approve-modification
           #:apply-modification
           #:rollback-modification
           #:pending-modifications
           #:applied-modifications
           #:modification-journal-summary
           ;; Image save/restore (I99)
           #:*image-directory-override*
           #:*image-max-count*
           #:*image-pre-save-hooks*
           #:*image-post-restore-hooks*
           #:image-directory
           #:rotate-images
           #:list-saved-images
           #:save-amoebum-image
           #:register-image-pre-save-hook
           #:register-image-post-restore-hook
           ;; ASDF extensions (I100)
           #:asdf-extension
           #:asdf-extension-p
           #:make-asdf-extension
           #:asdf-extension-system-name
           #:asdf-extension-description
           #:asdf-extension-version
           #:asdf-extension-status
           #:asdf-extension-loaded-at
           #:asdf-extension-permissions
           #:asdf-extension-source-path
           #:*asdf-extension-registry*
           #:*asdf-extension-search-paths*
           #:discover-asdf-extensions
           #:load-asdf-extension
           #:unload-asdf-extension
           #:reload-asdf-extension
           #:list-asdf-extensions
           #:find-asdf-extension
           #:clear-asdf-extensions
           #:save-asdf-extension-manifest
           #:load-asdf-extension-manifest
           ;; Profiler (I101)
           #:metrics-entry
           #:metrics-entry-p
           #:make-metrics-entry
           #:metrics-entry-kind
           #:metrics-entry-name
           #:metrics-entry-duration-ms
           #:metrics-entry-metadata
           #:metrics-store
           #:metrics-store-p
           #:make-metrics-store
           #:metrics-store-push
           #:metrics-store-recent
           #:metrics-store-clear
           #:metrics-store-count
           #:*global-metrics-store*
           #:record-metric
           #:with-tool-timing
           #:*gc-metrics-enabled-p*
           #:enable-gc-telemetry
           #:disable-gc-telemetry
           #:*profiler-running-p*
           #:profiler-start
           #:profiler-stop
           #:profiler-report
           #:profiler-reset
           #:memory-statistics
           #:metrics-summary
           ;; Swarm integration (I83-I93)
           #:swarm-agent
           #:swarm-agent-p
           #:make-swarm-agent
           #:swarm-agent-id
           #:swarm-agent-task
           #:swarm-agent-status
           #:swarm-agent-created-at
           #:swarm-agent-finished-at
           #:swarm-agent-state-machine
           #:swarm-agent-result
           #:swarm-agent-thread
           #:swarm-agent-error-message
           #:*swarm-registry*
           #:*swarm-counter*
           #:spawn-swarm-agent
           #:collect-swarm-result
           #:kill-swarm-agent
           #:list-swarm-agents
           #:find-swarm-agent
           #:clear-swarm-registry
           #:swarm-status-summary
           ;; Read orchestration (I105, re-exported for tests)
           #:read-orchestration-error
           #:validate-read-arguments
           #:orchestrate-read
           #:orchestrate-read-via-pipeline
           #:format-read-error-for-user
           #:*read-orchestration-max-line-limit*
           #:*read-orchestration-max-file-size-bytes*
           #:*read-orchestration-supported-extensions*
           ;; Write safety checks (I107)
           #:*write-forbidden-path-prefixes*
           #:*write-deny-filename-patterns*
           #:write-safety-denied
           #:write-safety-denied-path
           #:write-safety-denied-denial-reason
           #:check-write-safety
           #:write-safety-check-p
           ;; Edit validation (I109)
           #:edit-validation-error
           #:*edit-validation-enabled-p*
           #:*edit-validation-post-hooks*
           #:*edit-validation-content-hashes*
           #:validate-edit-preconditions
           #:validate-edit-postconditions
           #:register-post-edit-hook
           #:unregister-post-edit-hook
           #:clear-post-edit-hooks
           #:install-edit-validation-hooks
           #:uninstall-edit-validation-hooks
           ;; Shell environment handling (I111)
           #:*shell-env-sensitive-patterns*
           #:shell-environment
           #:shell-environment-p
           #:make-shell-environment
           #:shell-environment-cwd
           #:shell-environment-inherit-cwd-p
           #:shell-environment-env-overrides
           #:shell-environment-inherit-env-p
           #:shell-environment-filter-sensitive-p
           #:shell-environment-sensitive-patterns
           #:shell-environment-extra-path-dirs
           #:filter-sensitive-env
           #:resolve-shell-env-cwd
           #:assemble-shell-env
           #:shell-env-to-string-list
           #:merge-shell-environment
           #:describe-shell-environment
           ;; Shell safety policy hooks (I112)
           #:*shell-safety-deny-patterns*
           #:*shell-safety-escalate-patterns*
           #:+event-type-shell-command-blocked+
           #:+event-type-shell-command-escalated+
           #:shell-safety-result
           #:shell-safety-result-p
           #:shell-safety-result-decision
           #:shell-safety-result-reason
           #:shell-safety-result-matched-pattern
           #:evaluate-shell-safety-policy
           #:shell-safety-policy-hook
           #:shell-command-safe-p))

(defpackage :amoebum.sandbox
  (:use)
  (:import-from :cl
                #:+
                #:-
                #:*
                #:/
                #:<
                #:<=
                #:=
                #:>
                #:>=
                #:1+
                #:1-
                #:abs
                #:and
                #:append
                #:aref
                #:car
                #:cdr
                #:cadr
                #:caddr
                #:case
                #:coerce
                #:cond
                #:cons
                #:copy-list
                #:copy-seq
                #:defparameter
                #:defun
                #:destructuring-bind
                #:dolist
                #:dotimes
                #:eq
                #:equal
                #:eql
                #:error
                #:evenp
                #:every
                #:find
                #:first
                #:format
                #:fourth
                #:funcall
                #:if
                #:incf
                #:labels
                #:lambda
                #:last
                #:length
                #:let
                #:list
                #:list*
                #:loop
                #:mapcar
                #:max
                #:member
                #:min
                #:mod
                #:nconc
                #:not
                #:nth
                #:null
                #:numberp
                #:oddp
                #:or
                #:pop
                #:position
                #:progn
                #:push
                #:reduce
                #:remove
                #:rest
                #:reverse
                #:second
                #:setf
                #:some
                #:sort
                #:string
                #:string-downcase
                #:string-upcase
                #:string=
                #:subseq
                #:svref
                #:third
                #:unless
                #:values
                #:vector
                #:when)
  (:import-from :amoebum
                #:+sandbox-max-output-size+
                #:+sandbox-max-read-size+
                #:safe-open
                #:safe-run-program
                #:truncate-sandbox-output)
  (:export #:+sandbox-max-output-size+
           #:+sandbox-max-read-size+
           #:safe-open
           #:safe-run-program
           #:truncate-sandbox-output
           ;; Read orchestration (I105)
           #:read-orchestration-error
           #:validate-read-arguments
           #:orchestrate-read
           #:orchestrate-read-via-pipeline
           #:format-read-error-for-user
           #:*read-orchestration-max-line-limit*
           #:*read-orchestration-max-file-size-bytes*
           #:*read-orchestration-supported-extensions*))

(defpackage :amoebum.tools
  (:use :cl))

(defpackage :amoebum.internal
  (:use :cl))
