(defpackage :amoebum
  (:use :cl)
  (:export #:main
           #:deftool
           #:defhook
           #:defkeys
           #:defskill
           #:event
           #:event-p
           #:make-event
           #:event-type
           #:event-type-p
           #:event-seq
           #:event-ts-mono
           #:event-timestamp
           #:event-source
           #:event-severity
           #:event-payload
           #:event-bus
           #:event-bus-p
           #:make-event-bus
           #:current-event-bus
           #:*event-bus*
           #:event-history
           #:subscribe
           #:unsubscribe
           #:publish
           #:filter-by-type
           #:filter-by-severity
           #:filter-by-source
           #:filter-and
           #:filter-or
           #:filter-not
           #:filter-by-tool
           #:filter-by-permission-mode
           #:event-router
           #:+event-type-tool-invoked+
           #:+event-type-tool-completed+
           #:+event-type-tool-error+
           #:+event-type-tool-redefined+
           #:+event-type-config-changed+
           #:+event-type-permission-prompted+
           #:+event-type-permission-blocked+
           #:+event-type-memory-updated+
           #:+event-type-memory-backend-selected+
           #:+event-type-context-compressed+
           #:+event-type-mcp-tool-discovered+
           #:+event-type-mcp-tool-invoked+
           #:+event-type-keymap-overlay-enter+
           #:+event-type-keymap-overlay-exit+
           #:+event-type-extension-loaded+
           #:+event-type-extension-error+
           #:+event-type-llm-stream-chunk+
           #:+event-type-stream-budget-warning+
           #:+event-type-conversation-forked+
           #:+event-type-tool-call-started+
           #:+event-type-tool-call-argument-complete+
           #:+event-type-session-checkpointed+
           #:+event-type-session-restored+
           #:+event-type-plan-step-status+
           #:+event-type-git-commit+
           #:+event-type-git-branch+
           #:+event-type-agent-spawned+
           #:+event-type-agent-completed+
           #:+event-type-agent-error+
           #:+lifecycle-event-types+
           #:event-type-p
           #:+core-event-types+
           #:commit-event
           #:commit-event-p
           #:make-commit-event
           #:commit-event-hash
           #:commit-event-message
           #:commit-event-author
           #:commit-event-files-changed
           #:commit-event-event-type
           #:branch-event
           #:branch-event-p
           #:make-branch-event
           #:branch-event-old-branch
           #:branch-event-new-branch
           #:branch-event-action
           #:branch-event-event-type
           #:agent-spawned-event
           #:agent-spawned-event-p
           #:make-agent-spawned-event
           #:agent-spawned-event-event-type
           #:agent-completed-event
           #:agent-completed-event-p
           #:make-agent-completed-event
           #:agent-completed-event-elapsed-ms
           #:agent-error-event
           #:agent-error-event-p
           #:make-agent-error-event
           #:agent-error-event-event-type
           #:tool-invoked-payload
           #:tool-invoked-payload-p
           #:make-tool-invoked-payload
           #:tool-completed-payload
           #:tool-completed-payload-p
           #:make-tool-completed-payload
           #:tool-error-payload
           #:tool-error-payload-p
           #:make-tool-error-payload
           #:tool-error-payload-tool-name
           #:tool-error-payload-args
           #:tool-error-payload-condition
           #:tool-error-payload-condition-reason-code
           #:tool-error-payload-elapsed-ms
           #:tool-error-payload-request-id
           #:tool-redefined-payload
           #:tool-redefined-payload-p
           #:make-tool-redefined-payload
           #:tool-redefined-payload-tool-name
           #:tool-redefined-payload-old-metadata
           #:tool-redefined-payload-new-metadata
           #:tool-redefined-payload-metadata-diff
           #:config-changed-payload
           #:config-changed-payload-p
           #:make-config-changed-payload
           #:config-changed-payload-key
           #:config-changed-payload-old-value
           #:config-changed-payload-new-value
           #:permission-prompted-payload
           #:permission-prompted-payload-p
           #:make-permission-prompted-payload
           #:permission-prompted-payload-tool-name
           #:permission-prompted-payload-path
           #:permission-prompted-payload-command
           #:permission-prompted-payload-reason
           #:permission-prompted-payload-reason-code
           #:permission-prompted-payload-permission-mode
           #:permission-blocked-payload
           #:permission-blocked-payload-p
           #:make-permission-blocked-payload
           #:permission-blocked-payload-tool-name
           #:permission-blocked-payload-path
           #:permission-blocked-payload-command
           #:permission-blocked-payload-reason
           #:permission-blocked-payload-actionable-reason
           #:permission-blocked-payload-reason-code
           #:permission-blocked-payload-permission-mode
           #:memory-updated-payload
           #:memory-updated-payload-p
           #:make-memory-updated-payload
           #:memory-backend-selected-payload
           #:memory-backend-selected-payload-p
           #:make-memory-backend-selected-payload
           #:memory-backend-selected-payload-backend
           #:memory-backend-selected-payload-reason
           #:memory-backend-selected-payload-requested-backend
           #:context-compressed-payload
           #:context-compressed-payload-p
           #:make-context-compressed-payload
           #:mcp-tool-discovered-payload
           #:mcp-tool-discovered-payload-p
           #:make-mcp-tool-discovered-payload
           #:mcp-tool-invoked-payload
           #:mcp-tool-invoked-payload-p
           #:make-mcp-tool-invoked-payload
           #:extension-loaded-payload
           #:extension-loaded-payload-p
           #:make-extension-loaded-payload
           #:extension-loaded-payload-path
           #:extension-loaded-payload-scope
           #:extension-error-payload
           #:extension-error-payload-p
           #:make-extension-error-payload
           #:extension-error-payload-path
           #:extension-error-payload-scope
           #:extension-error-payload-condition
           #:llm-stream-chunk-payload
           #:llm-stream-chunk-payload-p
           #:make-llm-stream-chunk-payload
           #:llm-stream-chunk-payload-token
           #:llm-stream-chunk-payload-chunk-index
           #:llm-stream-chunk-payload-token-index
           #:llm-stream-chunk-payload-total-tokens
           #:stream-budget-warning-payload
           #:stream-budget-warning-payload-p
           #:make-stream-budget-warning-payload
           #:stream-budget-warning-payload-used-tokens
           #:stream-budget-warning-payload-limit-tokens
           #:stream-budget-warning-payload-usage-percent
           #:stream-budget-warning-payload-threshold-percent
           #:tool-call-started-payload
           #:tool-call-started-payload-p
           #:make-tool-call-started-payload
           #:tool-call-started-payload-tool-name
           #:tool-call-started-payload-tool-call-id
           #:tool-call-started-payload-arguments
           #:tool-call-started-payload-index
           #:tool-call-argument-complete-payload
           #:tool-call-argument-complete-payload-p
           #:make-tool-call-argument-complete-payload
           #:tool-call-argument-complete-payload-tool-name
           #:tool-call-argument-complete-payload-tool-call-id
           #:tool-call-argument-complete-payload-arguments
           #:tool-call-argument-complete-payload-index
           #:session-checkpointed-payload
           #:session-checkpointed-payload-p
           #:make-session-checkpointed-payload
           #:session-checkpointed-payload-checkpoint-id
           #:session-checkpointed-payload-path
           #:session-checkpointed-payload-trigger
           #:session-checkpointed-payload-auto-p
           #:session-checkpointed-payload-message-count
           #:session-checkpointed-payload-extension-count
           #:session-checkpointed-payload-tool-count
           #:session-checkpointed-payload-memory-count
           #:session-restored-payload
           #:session-restored-payload-p
           #:make-session-restored-payload
           #:session-restored-payload-checkpoint-id
           #:session-restored-payload-path
           #:session-restored-payload-trigger
           #:session-restored-payload-message-count
           #:session-restored-payload-extension-count
           #:session-restored-payload-tool-count
           #:session-restored-payload-memory-count
           #:plan-step-status-payload
           #:plan-step-status-payload-p
           #:make-plan-step-status-payload
           #:plan-step-status-payload-run-id
           #:plan-step-status-payload-step-index
           #:plan-step-status-payload-status
           #:plan-step-status-payload-description
           #:context-compressed-payload-before-tokens
           #:context-compressed-payload-after-tokens
           #:context-compressed-payload-saved-tokens
           #:context-compressed-payload-summarized-messages
           #:context-compressed-payload-kept-messages
           #:context-compressed-payload-trigger
           #:make-tool-invoked-event
           #:make-tool-completed-event
           #:make-tool-error-event
           #:make-tool-redefined-event
           #:make-config-changed-event
           #:make-permission-prompted-event
           #:make-permission-blocked-event
           #:make-memory-updated-event
           #:make-memory-backend-selected-event
           #:make-context-compressed-event
           #:make-mcp-tool-discovered-event
           #:make-mcp-tool-invoked-event
           #:make-extension-loaded-event
           #:make-extension-error-event
           #:make-llm-stream-chunk-event
           #:make-stream-budget-warning-event
           #:make-tool-call-started-event
           #:make-tool-call-argument-complete-event
           #:make-session-checkpointed-event
           #:make-session-restored-event
           #:make-plan-step-status-event
           #:+event-type-tool-started-event+
           #:+event-type-tool-completed-event+
           #:+event-type-tool-error-event+
           #:+event-type-llm-request-event+
           #:+event-type-llm-response-event+
           #:+event-type-conversation-step-event+
           #:+typed-event-types+
           #:tool-started-event
           #:tool-started-event-p
           #:make-tool-started-event
           #:tool-started-event-tool-name
           #:tool-started-event-arguments
           #:tool-started-event-timestamp
           #:tool-started-event-event-type
           #:tool-completed-event
           #:tool-completed-event-p
           #:make-tool-completed-event-type
           #:tool-completed-event-tool-name
           #:tool-completed-event-result
           #:tool-completed-event-elapsed-ms
           #:tool-completed-event-timestamp
           #:tool-completed-event-event-type
           #:tool-error-event
           #:tool-error-event-p
           #:make-tool-error-event-type
           #:tool-error-event-tool-name
           #:tool-error-event-condition
           #:tool-error-event-restarts
           #:tool-error-event-timestamp
           #:tool-error-event-event-type
           #:llm-request-event
           #:llm-request-event-p
           #:make-llm-request-event
           #:llm-request-event-provider
           #:llm-request-event-model
           #:llm-request-event-message-count
           #:llm-request-event-estimated-tokens
           #:llm-request-event-timestamp
           #:llm-request-event-event-type
           #:llm-response-event
           #:llm-response-event-p
           #:make-llm-response-event
           #:llm-response-event-provider
           #:llm-response-event-model
           #:llm-response-event-usage
           #:llm-response-event-latency-ms
           #:llm-response-event-timestamp
           #:llm-response-event-event-type
           #:conversation-step-event
           #:conversation-step-event-p
           #:make-conversation-step-event
           #:conversation-step-event-step-number
           #:conversation-step-event-role
           #:conversation-step-event-content-length
           #:conversation-step-event-timestamp
           #:conversation-step-event-event-type
           #:*toolset*
           #:*tool-metadata*
           #:*tool-history*
           #:tool-metadata-p
           #:tool-metadata-category
           #:tool-metadata-mcp-server
           #:setconfig
           #:+default-context-window-limit+
           #:+model-context-window-limits+
           #:+context-budget-green-threshold-percent+
           #:+context-budget-yellow-threshold-percent+
           #:+context-budget-compress-threshold-percent+
           #:*context-window-limit*
           #:context-window-limit-for-model
           #:resolve-context-window-limit
           #:context-usage-percent
           #:context-usage-level
           #:context-compression-required-p
           #:count-tokens
           #:plan-mode-state-steps
           #:plan-mode-state-approved-step-indexes
           #:plan-mode-state-review-pending-p
           #:plan-mode-state-review-decision
           #:plan-mode-state-review-notes
           #:plan-mode-state-review-last-presented-at
           #:plan-mode-state-last-plan-markdown
           #:plan-mode-state-last-output-path
           #:current-plan-mode-state
           #:plan-mode-active-p
           #:plan-step-indexes
           #:clear-plan-step-approvals
           #:reorder-plan-step
           #:set-plan-step-approvals
           #:approve-plan-steps
           #:plan-input-gating-snapshot
           #:set-plan-review-decision
           #:refresh-plan-review-markdown
           #:enter-plan-mode
           #:exit-plan-mode
           #:toggle-plan-mode
           ;; Approval dialog (interactive tool approval)
           #:pending-approval-decision
           #:wait-for-pending-approval
           #:make-approval-dialog-state
           #:approval-dialog-state-active-p
           #:approval-dialog-state-selected-option
           #:approval-dialog-activate!
           #:approval-dialog-deactivate!
           #:approval-dialog-move-selection!
           #:approval-dialog-confirm!
           #:approval-dialog-handle-key!
           #:make-approval-dialog-widget
           #:+event-type-agent-spawn+
           #:+event-type-agent-complete+
           #:+event-type-user-handoff-requested+
           #:+event-type-user-negotiation-artifact-submitted+
           #:+event-type-user-negotiation-critique-added+
           #:agent-record
           #:agent-record-p
           #:agent-record-id
           #:agent-record-parent-message-id
           #:agent-record-status
	           #:agent-record-worktree
	           #:agent-record-worktree-merge
           ;; Agent personas
           #:persona-definition
           #:persona-definition-p
           #:persona-definition-name
           #:persona-definition-description
           #:persona-definition-capabilities
           #:persona-definition-model
           #:persona-definition-system-prompt
           #:persona-definition-scope
           #:parse-persona-file
           #:find-persona-by-name
           #:persona-manifest-lines
           #:*agent-registry*
           #:clear-agents
           #:find-agent
           #:list-agents
           #:find-runtime-agent
           #:runtime-agent-backend
           #:runtime-agent-id
           #:runtime-agent-task
           #:runtime-agent-status
           #:runtime-agent-result
	           #:runtime-agent-error-message
	           #:runtime-agent-output
	           #:runtime-agent-worktree
	           #:runtime-agent-worktree-merge
	           #:runtime-agent-terminal-p
           #:spawn-agent
           #:agent-activity-entry
           #:agent-activity-entry-agent-id
           #:agent-activity-entry-activity-type
           #:agent-activity-entry-source-event-type
           #:ensure-agent-activity-stream
           #:clear-agent-activity-stream
           #:record-agent-activity
           #:list-agent-activity
           #:memory-backend
           #:file-memory-backend
           #:file-memory-backend-p
           #:make-file-memory-backend
           #:file-memory-backend-global-path
           #:file-memory-backend-project-path
           #:file-memory-backend-project-root
           #:haake-cli-memory-backend
           #:haake-cli-memory-backend-p
           #:make-haake-cli-memory-backend
           #:haake-cli-memory-backend-command
           #:haake-cli-memory-backend-project-id
           #:haake-cli-memory-backend-agent
           #:haake-cli-available-p
           #:haake-cli-status-ok-p
           #:haake-cli-compatible-p
           #:*haake-cli-command-runner*
           #:*haake-cli-availability-runner*
           #:*haake-cli-status-runner*
           #:*haake-cli-capability-runner*
           #:memory-entry
           #:memory-entry-p
           #:make-memory-entry
           #:memory-entry-key
           #:memory-entry-value
           #:memory-entry-scope
           #:memory-entry-source
           #:memory-entry-created-at
           #:memory-candidate
           #:memory-candidate-p
           #:make-memory-candidate
           #:memory-candidate-kind
           #:memory-candidate-text
           #:memory-candidate-key
           #:memory-candidate-confidence
           #:*memory-backend*
           #:*session-memory-entries*
           #:*memory-editor-runner*
           #:reset-memory-backend
           #:current-memory-backend
           #:session-memory-entries
           #:memory-store
           #:memory-query
           #:memory-list
           #:memory-delete
           #:memory-forget
           #:default-memory-editor-runner
           #:memory-command-input-p
           #:memory-command-show
           #:memory-command-edit
           #:memory-command-clear
           #:run-memory-command
           #:extract-durable-memory-candidate
           #:apply-memory-candidate
           #:*extension-hot-reload-thread*
           #:*extension-hot-reload-running-p*
           #:+extension-supported-permissions+
           #:*extension-safe-operations*
           #:slash-command
           #:make-slash-command-result
           #:*slash-command-registry*
           #:*slash-command-action-handlers*
           #:parse-slash-command
           #:parse-slash-command-arguments
           #:clear-slash-commands
           #:clear-slash-command-action-handlers
           #:register-slash-command
           #:register-slash-command-action-handler
           #:find-slash-command-action-handler
           #:find-slash-command
           #:list-slash-commands
           #:complete-slash-command-input
           #:dispatch-slash-command
           #:resolve-slash-command
           #:apply-slash-command-result-action
           #:register-builtin-slash-commands
           #:+hook-point-definitions+
           #:*hook-registry*
           #:register-hook
           #:unregister-hook
           #:list-hooks
           #:clear-hooks
           #:describe-hooks
           #:hook-metrics
           #:hook-trace
           #:clear-hook-trace
           #:run-hooks
           #:hook-chain
           #:malformed-key-binding
           #:malformed-key-binding-key-spec
           #:malformed-key-binding-reason
           #:keymap-definition-warning
           #:keymap-definition-warning-keymap
           #:keymap-definition-warning-key-spec
           #:keymap-definition-warning-reason
           #:key-binding
           #:key-binding-p
           #:key-binding-signature
           #:key-binding-handler
           #:key-binding-guard
           #:key-binding-description
           #:key-binding-source-file
           #:key-binding-source-line
           #:key-chord
           #:key-chord-p
           #:key-chord-sequence
           #:key-chord-handler
           #:key-chord-guard
           #:key-chord-description
           #:key-chord-source-file
           #:key-chord-source-line
           #:keymap
           #:keymap-p
           #:keymap-overlay
           #:keymap-overlay-p
           #:keymap-overlay-keymap
           #:keymap-overlay-auto-cleanup-on-escape-p
           #:keymap-overlay-entered-at
           #:make-keymap
           #:keymap-name
           #:keymap-description
           #:keymap-bindings
           #:keymap-chords
           #:*keymap-registry*
           #:*keymap-stack*
           #:*keymap-overlay-stack*
           #:*key-sequence-buffer*
           #:*key-sequence-timeout-ms*
           #:*key-disambiguation-timeout-ms*
           #:*terminal-key-normalization-profile*
           #:*terminal-key-normalization-table*
           #:register-keymap
           #:list-keymaps
           #:find-keymap
           #:clear-keymaps
           #:register-key-binding
           #:keymap-bindings-list
           #:define-chord
           #:push-keymap
           #:pop-keymap
           #:current-keymap
           #:current-keymap-overlay
           #:push-keymap-overlay
           #:pop-keymap-overlay
           #:clear-keymap-overlays
           #:reset-keymap-stack
           #:dispatch-key-event
           #:dispatch-active-keymaps
           #:flush-key-dispatch-timeouts
           #:resolve-terminal-key-normalization-profile
           #:make-key-dispatch-on-event
           #:activate-default-keymaps
           #:*chat-mode-keymap*
           #:*command-mode-keymap*
           #:*diff-mode-keymap*
           #:amoebum-error
           #:amoebum-error-message
           #:tool-error
           #:tool-error-reason
           #:tool-error-reason-code
           #:tool-execution-error
           #:tool-timeout
           #:tool-timeout-error
           #:tool-permission-denied
           #:tool-not-found
           #:tool-not-found-error
           #:capability-gap
           #:capability-gap-capability-name
           #:capability-gap-recovery-contract
           #:tool-argument-error
           #:tool-missing-argument
           #:tool-type-mismatch
           #:hook-execution-error
           #:mcp-timeout
           #:mcp-timeout-request-id
           #:mcp-timeout-timeout-seconds
           #:mcp-tool-bridge-error
           #:mcp-tool-bridge-error-server-name
           #:mcp-tool-bridge-error-mcp-tool-name
           #:mcp-tool-bridge-error-mcp-error-code
           #:mcp-tool-bridge-error-mcp-response-error
           #:*mcp-jsonrpc-default-timeout-seconds*
           #:mcp-jsonrpc-client
           #:mcp-jsonrpc-client-p
           #:make-mcp-jsonrpc-client
           #:mcp-jsonrpc-client-input-stream
           #:mcp-jsonrpc-client-output-stream
           #:mcp-jsonrpc-client-default-timeout-seconds
           #:mcp-jsonrpc-client-reader-running-p
           #:mcp-jsonrpc-client-reader-error
           #:make-jsonrpc-request-message
           #:make-jsonrpc-notification-message
           #:make-jsonrpc-response-message
           #:jsonrpc-serialize-message
           #:jsonrpc-deserialize-message
           #:jsonrpc-frame-message
           #:jsonrpc-write-message
           #:jsonrpc-read-message
           #:mcp-jsonrpc-send-message
           #:mcp-jsonrpc-send-notification
           #:mcp-jsonrpc-send-request
           #:mcp-jsonrpc-start-reader
           #:mcp-jsonrpc-stop-reader
           #:mcp-jsonrpc-poll
           #:mcp-jsonrpc-handle-incoming-message
           #:mcp-jsonrpc-drain-notifications
           #:*mcp-server-initialize-timeout-seconds*
           #:*mcp-server-ping-timeout-seconds*
           #:*mcp-server-health-check-interval-seconds*
           #:*mcp-server-restart-backoff-base-seconds*
           #:*mcp-server-restart-backoff-max-seconds*
           #:*mcp-server-shutdown-grace-seconds*
           #:mcp-server
           #:mcp-server-p
           #:make-mcp-server
           #:mcp-server-name
           #:mcp-server-transport
           #:mcp-server-command
           #:mcp-server-args
           #:mcp-server-cwd
           #:mcp-server-endpoint-url
           #:mcp-server-http-headers
           #:mcp-server-initialize-timeout-seconds
           #:mcp-server-ping-timeout-seconds
           #:mcp-server-health-check-interval-seconds
           #:mcp-server-restart-backoff-base-seconds
           #:mcp-server-restart-backoff-max-seconds
           #:mcp-server-shutdown-grace-seconds
           #:mcp-server-auto-restart-p
           #:mcp-server-running-p
           #:mcp-server-process
           #:mcp-server-jsonrpc-client
           #:mcp-server-server-info
           #:mcp-server-monitor-thread
           #:mcp-server-restart-count
           #:mcp-server-last-error
           #:mcp-server-start
           #:mcp-server-stop
           #:mcp-server-health-check
           #:mcp-server-restart
           #:*mcp-protocol-version*
           #:*mcp-negotiation-request-function*
           #:mcp-server-info
           #:mcp-server-info-p
           #:make-mcp-server-info
           #:mcp-server-info-protocol-version
           #:mcp-server-info-protocol-version-match-p
           #:mcp-server-info-capabilities
           #:mcp-server-info-tools-capability
           #:mcp-server-info-resources-capability
           #:mcp-server-info-prompts-capability
           #:mcp-server-info-logging-capability
           #:mcp-server-info-declared-tools
           #:mcp-server-info-discovered-tool-count
           #:mcp-server-info-negotiated-at-unix-time
           #:mcp-build-initialize-params
           #:mcp-negotiate-server-capabilities
           #:mcp-server-tool-declared-p
           #:mcp-update-server-discovered-tool-count
           #:mcp-server-capability-summary
           #:*mcp-tool-server-registry*
           #:*mcp-tool-binding-registry*
           #:*mcp-tools-list-request-function*
           #:mcp-tool-binding
           #:mcp-tool-binding-p
           #:mcp-tool-binding-server-name
           #:mcp-tool-binding-tool-name
           #:mcp-tool-binding-namespaced-name
           #:mcp-tool-binding-description
           #:mcp-tool-binding-input-schema
           #:mcp-tool-binding-server
           #:clear-mcp-tool-registries
           #:register-mcp-tool-server
           #:unregister-mcp-tool-server
           #:find-mcp-tool-server
           #:discover-mcp-server-tools
           #:invoke-mcp-tool-bridge
           #:invoke-mcp-tool
           #:auto-register-mcp-server-tools
           #:mcp-tool-name-for-amoebum-tool
           #:amoebum-tool-name-for-mcp-tool
           #:*lsp-server-initialize-timeout-seconds*
           #:*lsp-request-timeout-seconds*
           #:*lsp-server-restart-backoff-base-seconds*
           #:*lsp-server-restart-backoff-max-seconds*
           #:*lsp-server-shutdown-grace-seconds*
           #:*lsp-default-server-specs*
           #:*lsp-process-spawner*
           #:lsp-server-spec
           #:lsp-server-spec-p
           #:make-lsp-server-spec
           #:lsp-server-spec-name
           #:lsp-server-spec-language-id
           #:lsp-server-spec-command
           #:lsp-server-spec-args
           #:lsp-server-spec-file-extensions
           #:lsp-document-state
           #:lsp-document-state-p
           #:make-lsp-document-state
           #:lsp-document-state-path
           #:lsp-document-state-uri
           #:lsp-document-state-language-id
           #:lsp-document-state-text
           #:lsp-document-state-version
           #:lsp-server-connection
           #:lsp-server-connection-p
           #:lsp-server-connection-spec
           #:lsp-server-connection-process
           #:lsp-server-connection-jsonrpc-client
           #:lsp-server-connection-open-documents
           #:lsp-server-connection-restart-count
           #:lsp-server-connection-last-error
           #:lsp-client
           #:lsp-client-p
           #:make-lsp-client
           #:lsp-client-project-root
           #:lsp-client-server-specs
           #:lsp-client-initialize-timeout-seconds
           #:lsp-client-request-timeout-seconds
           #:lsp-client-restart-backoff-base-seconds
           #:lsp-client-restart-backoff-max-seconds
           #:lsp-client-shutdown-grace-seconds
           #:lsp-client-auto-restart-p
           #:lsp-language-id-for-path
           #:lsp-server-spec-for-path
           #:lsp-client-connection
           #:lsp-client-ensure-server
           #:lsp-open-document
           #:lsp-send-notification
           #:lsp-send-request
           #:lsp-request-document-symbols
           #:lsp-request-workspace-symbols
           #:lsp-drain-notifications
           #:lsp-client-stop
           #:context-overflow-error
           #:context-overflow-used-tokens
           #:context-overflow-max-tokens
           #:budget-exceeded-error
           #:budget-exceeded-kind
           #:budget-exceeded-used
           #:budget-exceeded-budget
           #:budget-exhausted-condition
           #:budget-exhausted-kind
           #:budget-exhausted-used
           #:budget-exhausted-budget
           #:budget-exhausted-context-summary
           #:condition-to-llm-context
           #:+tool-restart-names+
           #:+budget-restart-names+
           #:*supervised-restart-selector*
           #:*budget-exhaustion-restart-selector*
           #:*capability-gap-delegation-function*
           #:*capability-gap-install-function*
           #:default-supervised-restart-selector
           #:default-budget-exhaustion-restart-selector
           #:parse-recovery-decision
           #:apply-user-recovery-decision
           #:handle-budget-exhaustion
           #:execute-tool-with-restarts
           #:tool-execution-context
           #:amoebum-context
           #:make-amoebum-context
           #:context-permission-mode
           #:context-hook-registry
           #:context-metrics
           #:execute-tool
           #:context-tool-metrics
           #:cached-tool-result
           ;; Policy types (NXT-127)
           #:make-policy-trace-entry
           #:policy-trace-entry-phase
           #:policy-trace-entry-source
           #:policy-trace-entry-decision
           #:policy-trace-entry-reason-code
           #:policy-trace-entry-reason
           #:policy-trace-entry-data
           #:policy-trace-entry-timestamp
           #:policy-decision-context
           #:policy-decision-context-kind
           #:policy-decision-context-tool-name
           #:policy-decision-context-path
           #:policy-decision-context-command
           #:policy-decision-context-permission-mode
           #:policy-decision-context-plan-step-index
           #:policy-decision-context-plan-event
           #:policy-decision-context-plist
           #:make-policy-rule-table
           #:policy-rule-table-name
           #:policy-rule-table-source
           #:policy-rule-table-rule-count
           #:policy-rule-table-find-rule
           #:make-policy-rule-registry
           #:policy-rule-registry-layers
           #:policy-rule-registry-layer-count
           #:policy-rule-registry-rule-count
           #:policy-rule-registry-find-layer
           #:policy-rule-registry-composed-rules
           #:plan-execution-transition-structured-trace
           #:plan-execution-effect-type-registered-p
           #:plan-execution-effect-type-metadata
           #:register-plan-execution-effect-type
           #:publish-plan-execution-transition-event
           #:replay-permission-decision-from-trace
           #:format-policy-trace-report
           #:diff-permission-decisions
           #:make-permission-rule
           #:command-canonical-form-normalized
           #:command-canonical-form-argv
           #:command-canonical-form-operators
           #:command-canonical-form-ast
           #:command-canonical-form-operator-metadata
           #:command-canonical-form-canonical-signature
           #:command-canonical-form-dangerous-reason-codes
           #:path-approval-entry-tool
           #:path-approval-entry-path
           #:*permission-rules*
           #:*path-approval-memory*
           #:add-permission-rule
           #:canonicalize-permission-command
           #:command-canonicalization-trace
           #:permission-command-argument-profile
           #:normalize-permission-path
           #:evaluate-path-permission
           #:evaluate-command-permission
           #:path-approval-store-path
           #:load-path-approvals
           #:clear-path-approvals
           #:list-path-approvals
           #:remember-path-approval
           #:dangerous-command-p
           #:plan-mode-mutating-tools-blocked-p
           #:check-permission
           #:last-permission-decision-trace
           #:+sandbox-max-output-size+
           #:+sandbox-max-read-size+
           #:sandbox-violation
           #:sandbox-violation-operation
           #:sandbox-violation-reason
           #:sandbox-violation-details
           #:sandbox-read-eval-disabled
           #:sandbox-read-eval-disabled-form
           #:sandbox-read-size-exceeded
           #:sandbox-read-size-exceeded-path
           #:sandbox-read-size-exceeded-size-bytes
           #:sandbox-read-size-exceeded-limit-bytes
           #:normalize-sandbox-policy
           #:sandbox-policy
           #:sandbox-policy-enabled-p
           #:*sandbox-enforcement-rules*
           #:sandbox-check-tool-call
           #:safe-open
           #:safe-run-program
           #:truncate-sandbox-output
           #:apply-sandbox-output-guard
           #:make-restricted-readtable
           #:*sandbox-restricted-readtable*
           #:sandbox-read-from-string
           #:+system-prompt-base-layer+
           #:resolve-system-prompt-layers
           #:system-prompt-dynamic-context
           #:assemble-system-prompt
           #:+chat-stream-default-system-prompt+
           #:+stream-cursor-glyph+
           #:+stream-cursor-blink-ms+
           #:+stream-budget-warning-threshold-percent+
           #:+stream-budget-abort-threshold-percent+
           #:stream-stats
           #:stream-stats-tokens-received
           #:stream-stats-chunks-processed
           #:stream-stats-elapsed-ms
           #:stream-stats-aborted-p
           #:stream-stats-abort-reason
           #:make-token-stream-state
           ;; NXT-129: Stream event journal
           #:make-stream-event-journal
           #:stream-event-journal-append!
           #:stream-event-journal-append-policy-trace!
           #:stream-event-journal-count
           #:stream-event-journal-clear!
           #:stream-event-journal-entries-list
           #:token-stream-active-p
           #:token-stream-cancel-requested-p
           #:token-stream-request-cancel
           #:token-stream-check-cancel
           #:token-stream-transition
           #:token-stream-set-target-message-index
           ;; YAML Theme System
           #:token-stream-set-budget-warning-threshold
           #:token-stream-abort
           #:token-stream-maybe-budget-warning
           #:token-stream-emit-chunk
           #:token-stream-emit-tool-call-started
           #:token-stream-emit-tool-call-argument-complete
           #:token-stream-emit-tool-call-result
           #:token-stream-mark-complete
           #:token-stream-mark-cancelled
           #:token-stream-drain-events
           #:token-stream-progress-summary
           #:token-stream-stats
           #:make-streaming-markdown-renderer
           #:streaming-markdown-renderer-append-chunk
           #:streaming-markdown-renderer-render-lines
           #:publish-status-bar-stream-summary
           #:*model-router*
           #:provider-health-entry-name
           #:provider-health-entry-status
           #:provider-health-monitor-reset!
           #:provider-health-refresh!
           #:provider-health-entries
           #:provider-health-compact-indicator
           #:chat-ui-state-stream-event-journal
           #:ensure-chat-ui-state
           #:make-chat-message
           #:chat-ui-add-message
           #:chat-ui-set-input
           #:chat-ui-submit-input
           #:chat-ui-scroll-history
           #:chat-ui-build-tree
           #:render-chat-ui-buffer
           #:run-chat-ui
           ;; Indexer (I96)
           ;; Self-modify (I98)
           #:+event-type-self-modify-proposed+
           #:+event-type-self-modify-approved+
           #:+event-type-self-modify-applied+
           #:+event-type-self-modify-rolled-back+
           #:modification-entry
           #:modification-entry-p
           #:make-modification-entry
           #:modification-entry-id
           #:modification-entry-form-text
           #:modification-entry-result
           #:modification-entry-status
           #:modification-entry-timestamp
           #:modification-entry-agent-id
           #:modification-entry-applied-symbols
           #:modification-entry-approval-mode
           #:modification-entry-error-message
           #:*modification-journal*
           #:modification-journal
           #:clear-modification-journal
           #:find-modification
           #:sandboxed-eval
           #:*self-modify-auto-approve-p*
           #:*self-modify-auto-approve-prefixes*
           #:*self-modify-max-eval-seconds*
           #:*self-modify-max-cons-cells*
           #:*self-modification-audit-path-override*
           #:*self-modification-agent-id-override*
           #:self-modification-audit-path
           #:propose-modification
           #:approve-modification
           #:deny-modification
           #:edit-modification
           #:render-modification-approval-widget
           #:apply-modification
           #:rollback-modification
           #:undo-last-modification
           #:pending-modifications
           #:applied-modifications
           #:list-modifications
           #:modification-history-browser
           #:modification-journal-summary
           ;; Image save/restore (I99)
           #:*image-directory-override*
           #:*image-max-count*
           #:*image-pre-save-hooks*
           #:*image-post-restore-hooks*
           #:image-directory
           #:rotate-images
           #:list-saved-images
           #:save-amoebum-image
           #:register-image-pre-save-hook
           #:register-image-post-restore-hook
           ;; ASDF extensions (I100)
           #:asdf-extension
           #:asdf-extension-p
           #:make-asdf-extension
           #:asdf-extension-system-name
           #:asdf-extension-description
           #:asdf-extension-version
           #:asdf-extension-status
           #:asdf-extension-loaded-at
           #:asdf-extension-permissions
           #:asdf-extension-source-path
           #:*asdf-extension-registry*
           #:*asdf-extension-search-paths*
           #:discover-asdf-extensions
           #:load-asdf-extension
           #:unload-asdf-extension
           #:reload-asdf-extension
           #:list-asdf-extensions
           #:find-asdf-extension
           #:clear-asdf-extensions
           #:save-asdf-extension-manifest
           #:load-asdf-extension-manifest
           ;; Extension manifests + dependency resolver (I233)
           #:+extension-capabilities+
           #:extension-manifest
           #:extension-manifest-p
           #:make-extension-manifest
           #:extension-manifest-name
           #:extension-manifest-version
           #:extension-manifest-author
           #:extension-manifest-description
           #:extension-manifest-license
           #:extension-manifest-dependencies
           #:extension-manifest-capabilities
           #:extension-manifest-provides
           #:extension-manifest-entry-point
           #:extension-manifest-source-path
           #:parse-extension-manifest-sexp
           #:read-extension-manifest-file
           #:compare-extension-version
           #:version-satisfies-constraint-p
           #:resolve-extension-manifests
           ;; Profiler (I101)
           ;; Profiling dashboard (I236)
           ;; USDT/eBPF observability (I255)
           #:usdt-disabled-overhead-percent
           ;; Swarm integration (I83-I93) + NXT-017/NXT-018
           #:swarm-agent
           #:swarm-agent-p
           #:make-swarm-agent
           #:swarm-agent-id
           #:swarm-agent-status
           #:swarm-agent-finished-at
           #:swarm-agent-state-machine
           #:swarm-agent-result
           #:swarm-agent-error-message
           ;; NXT-017: signal tracking and retry semantics
           #:swarm-agent-signal-name
           #:swarm-agent-retry-count
           #:swarm-agent-retry-policy
           #:swarm-agent-timeout-seconds
           ;; NXT-018: stalled-run detection
	           #:swarm-agent-heartbeat-at
	           #:swarm-agent-last-output-at
	           #:swarm-agent-worktree
	           #:swarm-agent-worktree-merge
           #:spawn-swarm-agent
           #:collect-swarm-result
           #:kill-swarm-agent
           #:list-swarm-agents
           #:find-swarm-agent
           #:clear-swarm-registry
           #:swarm-status-summary
           ;; NXT-018: heartbeat/stall functions
           #:update-swarm-agent-heartbeat
           #:update-swarm-agent-last-output
           #:detect-stalled-agents
           ;; NXT-336: local SW4RM worktree runtime wrapper
           #:worktree-metadata
           #:worktree-metadata-p
           #:make-worktree-metadata
           #:worktree-metadata-id
           #:worktree-metadata-branch
           #:worktree-metadata-path
	           #:resolve-worktree-id
	           #:resolve-worktree-branch
	           #:resolve-worktree-workflow-branch
	           #:resolve-worktree-metadata
           #:worktree-runtime
           #:worktree-runtime-p
           #:worktree-runtime-repo-root
           #:worktree-runtime-scratch-root
           #:worktree-runtime-lock-root
           #:worktree-runtime-coordinator
           #:worktree-runtime-backend
           #:worktree-runtime-local-p
           #:worktree-runtime-remote-p
           #:make-worktree-runtime
           #:current-worktree-runtime
           #:default-worktree-repo-root
           #:default-worktree-scratch-root
           #:default-worktree-lock-root
           #:worktree-runtime-path
           #:spawn-worktree
           #:collect-worktree
           #:inspect-worktree
           #:merge-worktree
           #:kill-worktree
           #:spawn-local-worktree
           #:collect-local-worktree
           #:kill-local-worktree
           #:inspect-local-worktree
           #:mark-local-worktree-abandoned
	           #:cleanup-abandoned-local-worktree
	           #:cleanup-abandoned-local-worktrees
	           #:resolve-worktree-merge-target
	           #:preflight-local-worktree-merge
	           #:merge-local-worktree
	           #:create-worktree-conflict-handoff
	           #:clear-worktree-conflict-handoffs
	           #:list-worktree-conflict-handoffs
	           #:find-worktree-conflict-handoff
	           #:accept-worktree-conflict-handoff
	           #:defer-worktree-conflict-handoff
	           #:resolve-worktree-conflict-handoff
	           #:abandon-worktree-conflict-handoff
	           ;; Inter-user coordination (I253)
           #:register-user-session-peer
           #:find-user-session-peer
           #:list-user-session-peers
           #:+event-type-user-handoff-requested+
           #:+event-type-user-negotiation-artifact-submitted+
           #:+event-type-user-negotiation-critique-added+
           #:handoff-between-users
           #:get-user-pending-handoffs
           #:user-handoff-status
           #:accept-user-handoff
           #:reject-user-handoff
           #:complete-user-handoff
           #:create-user-negotiation-room
           #:submit-user-negotiation-artifact
           #:add-user-negotiation-critique
           #:get-user-negotiation-room-status
           #:wait-for-user-negotiation-decision
           ;; Read orchestration (I105, re-exported for tests)
           #:read-orchestration-error
           #:validate-read-arguments
           #:orchestrate-read
           #:orchestrate-read-via-pipeline
           #:format-read-error-for-user
           #:+event-type-read-orchestration-cache+
           #:clear-read-orchestration-cache
           #:read-orchestration-cache-metrics
           #:*read-orchestration-max-line-limit*
           ;; Write safety checks (I107)
           #:write-safety-denied
           #:write-safety-denied-path
           #:write-safety-denied-denial-reason
           #:check-write-safety
           #:write-safety-check-p
           ;; Edit validation (I109)
           #:edit-validation-error
           #:*edit-validation-post-hooks*
           #:*edit-validation-content-hashes*
           #:validate-edit-preconditions
           #:validate-edit-postconditions
           #:register-post-edit-hook
           #:unregister-post-edit-hook
           #:clear-post-edit-hooks
           #:install-edit-validation-hooks
           #:uninstall-edit-validation-hooks
           ;; Shell environment handling (I111)
           #:shell-environment-p
           #:make-shell-environment
           #:shell-environment-cwd
           #:shell-environment-inherit-cwd-p
           #:shell-environment-env-overrides
           #:shell-environment-inherit-env-p
           #:shell-environment-filter-sensitive-p
           #:shell-environment-sensitive-patterns
           #:shell-environment-extra-path-dirs
           #:filter-sensitive-env
           #:load-project-env-overrides
           #:default-project-path-augmentation-dirs
           #:resolve-shell-env-cwd
           #:assemble-shell-env
           #:shell-env-to-string-list
           #:merge-shell-environment
           #:describe-shell-environment
           ;; Shell safety policy hooks (I112)
           ;; Sound backend protocol (I257)
           #:play-sound
           ;; Worker-supervisor protocol (I258)
           #:worker-record-worktree
           #:+event-type-worker-spawned+
           #:+event-type-worker-started+
           #:+event-type-worker-completed+
           #:+event-type-worker-failed+
           #:+event-type-worker-cancelled+
           #:+event-type-worker-retry+
           #:supervisor-spawn
           #:supervisor-status
           #:supervisor-result
           #:supervisor-cancel
           #:supervisor-list
           #:supervisor-output
           #:in-process-supervisor
           #:*worker-supervisor*
           #:ensure-worker-supervisor
           #:spawn-worker
           #:worker-status
           #:worker-result
           #:worker-cancel
           #:active-worker-count
           #:clear-workers
           #:await-any-worker
           ;; Overwatch worker backend (I259)
           #:*overwatch-host*
           #:*overwatch-port*
           #:*overwatch-poll-interval-seconds*
           #:*overwatch-connect-timeout-seconds*
           #:*overwatch-http-request-function*
           #:overwatch-supervisor
           #:overwatch-available-p
           #:select-worker-backend
           ;; Event journal (I263)
           #:*journal-directory*
           #:*journal-max-segment-bytes*
           #:*journal-max-segment-seconds*
           #:*journal-max-segments*
           #:*journal-flush-interval-events*
           #:journal-segment
           #:journal-segment-p
           #:journal-segment-path
           #:journal-segment-created-at
           #:journal-segment-closed-at
           #:journal-segment-event-count
           #:journal-segment-byte-count
           #:event-journal
           #:event-journal-p
           #:event-journal-directory
           #:event-journal-running-p
           #:event-journal-total-events
           #:event-journal-segments
           #:event-journal-active-segment
           #:*event-journal*
           #:make-event-journal-instance
           #:start-event-journal
           #:stop-event-journal
           #:journal-statistics
           #:journal-segment-paths
           #:reset-event-journal
           ;; Worker retry and supervision (I260)
           #:worker-supervision-policy
           #:worker-supervision-policy-p
           #:make-worker-supervision-policy
           #:worker-supervision-policy-max-retries
           #:worker-supervision-policy-backoff-strategy
           #:worker-supervision-policy-backoff-base-seconds
           #:worker-supervision-policy-transient-exit-codes
           #:*default-supervision-policy*
           #:classify-worker-failure
           #:worker-retry-eligible-p
           #:spawn-worker-supervised
           #:child-worker-failed
           #:supervise-child-worker
           ;; Worker fan-out and join (I261)
           #:fan-out-workers
           #:merge-worker-results
           ;; Event replay and audit (I264)
           #:replay-journal
           #:audit-query
           #:audit-current-journal
           #:replay-current-journal
           ;; Session recording (I265)
           ;; Conversation export (I266)
           ;; Worker dashboard (I262)
           #:ensure-worker-dashboard-state
           #:agent-activity-stream
           ;; NXT-092: IDE context ingestion
           #:ide-context-p
           #:make-ide-context
           #:ide-context-selections
           #:ide-context-diagnostics
           #:ide-context-open-files
           #:ide-context-active-file
           #:ide-context-timestamp
           #:*ide-context*
           #:update-ide-context!
           #:ide-context-summary
           #:ide-context-token-estimate
           ;; NXT-093: IDE context -> prompt / status-bar
           #:ide-context-prompt-fragment
           ;; NXT-094/NXT-095: IDE context integration and observability
           #:clear-ide-context!
           #:ide-context-prompt-fragment/budget
           #:+event-type-ide-context-attached+
           #:+event-type-ide-context-truncated+
           #:+event-type-ide-context-dropped+
           #:+event-type-watch-triggered+
           #:+event-type-nudge-triggered+
           #:ide-context-attached-payload-p
           #:ide-context-attached-payload-active-file
           #:ide-context-attached-payload-open-file-count
           #:ide-context-truncated-payload-p
           #:ide-context-truncated-payload-token-estimate
           #:ide-context-truncated-payload-token-budget
           #:ide-context-truncated-payload-diagnostics-dropped
           #:ide-context-dropped-payload-p
           #:ide-context-dropped-payload-active-file
           ;; NXT-106: Cultivar adapter
           #:cultivar-adapter-p
           #:make-cultivar-adapter
           #:cultivar-adapter-endpoint
           #:cultivar-adapter-enabled-p
           #:*cultivar-adapter*
           #:cultivar-resolve
           #:cultivar-location-slice
           #:cultivar-slice
           #:cultivar-preview
           #:cultivar-expand
           #:cultivar-daemon-status
           #:cultivar-cl-health-status
           ;; NXT-109: Cultivar context pressure
           #:cultivar-context-pressure
           ;; NXT-107: Yore adapter
           #:yore-adapter-p
           #:make-yore-adapter
           #:yore-adapter-endpoint
           #:yore-adapter-enabled-p
           #:*yore-adapter*
           #:yore-search-context
           #:yore-fetch-context
           ;; NXT-109: Yore context pressure + combined summary
           #:yore-context-pressure
           ;; NXT-108: IDE context packet builder
           #:ide-context-build-packet))
