(in-package :amoebum)

(defun %git-parse-status-porcelain (lines)
  (let ((branch "HEAD")
        (upstream nil)
        (ahead 0)
        (behind 0)
        (staged '())
        (unstaged '())
        (untracked '()))
    (labels ((push-unique (item list)
               (if (or (null item)
                       (zerop (length item))
                       (member item list :test #'string=))
                   list
                   (cons item list)))
             (tracked-path (line rename-p)
               (let ((parts (%git-split-whitespace line)))
                 (if rename-p
                     (and (>= (length parts) 3)
                          (nth (- (length parts) 2) parts))
                     (car (last parts))))))
      (dolist (line lines)
        (cond
          ((uiop:string-prefix-p "# branch.head " line)
           (setf branch (%git-trim-whitespace (subseq line (length "# branch.head ")))))
          ((uiop:string-prefix-p "# branch.upstream " line)
           (setf upstream (%git-trim-whitespace (subseq line (length "# branch.upstream ")))))
          ((uiop:string-prefix-p "# branch.ab " line)
           (let* ((parts (%git-split-whitespace line))
                  (ahead-token (or (third parts) "+0"))
                  (behind-token (or (fourth parts) "-0")))
             (setf ahead (%git-safe-parse-int (subseq ahead-token 1))
                   behind (%git-safe-parse-int (subseq behind-token 1)))))
          ((uiop:string-prefix-p "? " line)
           (let ((path (%git-normalize-change-path (subseq line 2))))
             (setf untracked (push-unique path untracked)
                   unstaged (push-unique path unstaged))))
          ((or (uiop:string-prefix-p "1 " line)
               (uiop:string-prefix-p "2 " line)
               (uiop:string-prefix-p "u " line))
           (let* ((parts (%git-split-whitespace line))
                  (xy (or (second parts) ".."))
                  (x (if (> (length xy) 0) (char xy 0) #\.))
                  (y (if (> (length xy) 1) (char xy 1) #\.))
                  (rename-p (uiop:string-prefix-p "2 " line))
                  (path (%git-normalize-change-path (tracked-path line rename-p))))
             (when (and path (> (length path) 0))
               (unless (char= x #\.)
                 (setf staged (push-unique path staged)))
               (unless (char= y #\.)
                 (setf unstaged (push-unique path unstaged)))))))))
    (list :branch branch
          :tracking (list :upstream upstream
                          :ahead ahead
                          :behind behind
                          :tracking-p (not (null upstream)))
          :staged (nreverse staged)
          :unstaged (nreverse unstaged)
          :untracked (nreverse untracked))))

(defun %git-status-data (&key project-root)
  (let* ((root (%git-ensure-work-tree (%git-project-root project-root)))
         (result (%git-run-command-or-error root '("status" "--porcelain=2" "--branch")))
         (parsed (%git-parse-status-porcelain (%git-lines (getf result :stdout)))))
    (%git-publish-lifecycle-event
     +event-type-git-branch+
     (make-branch-event :old-branch nil
                        :new-branch (getf parsed :branch)
                        :action :status)
     :severity :debug)
    (append (list :project-root (coerce-path-string root)) parsed)))
