(in-package :amoebum)

;;; ---------------------------------------------------------------------------
;;; Profiling Dashboard (I236)
;;;
;;; SBCL statistical profiling report model, slash-command helpers, and
;;; TUI table rendering with sortable columns.
;;; ---------------------------------------------------------------------------

(defstruct (profiling-report
            (:constructor make-profiling-report
                (&key
                   (top-functions '())
                   (call-graph '())
                   (total-samples 0)
                   (elapsed-ms 0)
                   raw-report-text)))
  (top-functions '() :type list)
  (call-graph '() :type list)
  (total-samples 0 :type integer)
  (elapsed-ms 0 :type integer)
  raw-report-text)

(defvar *profiling-enabled-p* nil
  "When T, profiling collection is active.")

(defvar *tool-profiling-enabled-p* nil
  "When T, execute-tool timing is captured into profiling aggregates.")

(defvar *profiling-start-ms* 0
  "Monotonic timestamp in milliseconds when profiling started.")

(defvar *last-profiling-report* nil
  "Most recent profiling-report generated by stop-profiling/report-profiling.")

(defvar *tool-profile-stats* (make-hash-table :test #'equal)
  "Tool-name -> plist (:samples n :elapsed-ms n).")

(defvar *tool-profile-call-graph* (make-hash-table :test #'equal)
  "Cons(caller . callee) -> sample count for call-graph display.")

(defun %profiling-now-ms ()
  (truncate (* 1000
               (/ (coerce (get-internal-real-time) 'double-float)
                  (coerce internal-time-units-per-second 'double-float)))))

(defun %profiling-reset-tool-aggregates ()
  (clrhash *tool-profile-stats*)
  (clrhash *tool-profile-call-graph*)
  t)

(defun %tool-profile-entry (name)
  (or (gethash name *tool-profile-stats*)
      (setf (gethash name *tool-profile-stats*)
            (list :samples 0 :elapsed-ms 0))))

(defun note-tool-profiling-sample (tool-name elapsed-ms &key (caller "execute-tool"))
  "Record a single tool execution sample for profiling report aggregation."
  (when *tool-profiling-enabled-p*
    (let* ((name (string-downcase (string-trim '(#\Space #\Tab #\Newline #\Return)
                                               (princ-to-string tool-name))))
           (entry (%tool-profile-entry name))
           (edge-key (cons (princ-to-string caller) name)))
      (incf (getf entry :samples 0))
      (incf (getf entry :elapsed-ms 0) (max 0 (truncate elapsed-ms)))
      (setf (gethash edge-key *tool-profile-call-graph*)
            (1+ (gethash edge-key *tool-profile-call-graph* 0)))))
  t)

(defun start-profiling (&key (mode :cpu) (sample-interval 0.01) (tool-profiling t))
  "Start sb-sprof statistical profiling and reset report aggregates."
  (%profiling-reset-tool-aggregates)
  (setf *profiling-start-ms* (%profiling-now-ms)
        *last-profiling-report* nil
        *profiling-enabled-p* t
        *tool-profiling-enabled-p* (not (null tool-profiling)))
  (profiler-start :mode mode :sample-interval sample-interval)
  t)

(defun %capture-sprof-report-text (&key (type :flat))
  (with-output-to-string (out)
    (profiler-report :stream out :type type)))

(defun %safe-parse-integer (value)
  (ignore-errors
    (parse-integer value)))

(defun %safe-parse-float (value)
  (let ((number (ignore-errors (read-from-string value))))
    (if (numberp number)
        (float number 1.0d0)
        0.0d0)))

(defun %parse-sprof-function-line (line)
  (or
   (let ((groups (cl-ppcre:scan-to-strings
                  "^\\s*([0-9]+(?:\\.[0-9]+)?)%\\s+([0-9]+)\\s+(.+?)\\s*$"
                  line)))
     (when groups
       (list :name (string-trim '(#\Space #\Tab) (aref groups 2))
             :samples (or (%safe-parse-integer (aref groups 1)) 0)
             :percentage (%safe-parse-float (aref groups 0)))))
   (let ((groups (cl-ppcre:scan-to-strings
                  "^\\s*([0-9]+)\\s+([0-9]+(?:\\.[0-9]+)?)%\\s+(.+?)\\s*$"
                  line)))
     (when groups
       (list :name (string-trim '(#\Space #\Tab) (aref groups 2))
             :samples (or (%safe-parse-integer (aref groups 0)) 0)
             :percentage (%safe-parse-float (aref groups 1)))))))

(defun %parse-sprof-call-edge (line)
  (let ((groups (cl-ppcre:scan-to-strings
                 "^\\s*(.+?)\\s*->\\s*(.+?)\\s*(?:\\(([0-9]+)\\))?\\s*$"
                 line)))
    (when groups
      (list :caller (string-trim '(#\Space #\Tab) (aref groups 0))
            :callee (string-trim '(#\Space #\Tab) (aref groups 1))
            :samples (or (%safe-parse-integer (or (aref groups 2) "0")) 0)))))

(defun %tool-stats->top-functions ()
  (let ((rows '())
        (total 0))
    (maphash (lambda (name entry)
               (declare (ignore name))
               (incf total (getf entry :samples 0)))
             *tool-profile-stats*)
    (maphash
     (lambda (name entry)
       (let ((samples (getf entry :samples 0)))
         (push (list :name name
                     :samples samples
                     :percentage (if (plusp total)
                                     (* 100.0d0 (/ samples total))
                                     0.0d0))
               rows)))
     *tool-profile-stats*)
    (values (nreverse rows) total)))

(defun %tool-stats->call-graph ()
  (let ((edges '()))
    (maphash (lambda (key samples)
               (push (list :caller (car key)
                           :callee (cdr key)
                           :samples samples)
                     edges))
             *tool-profile-call-graph*)
    (nreverse edges)))

(defun %collect-top-functions-from-text (text)
  (let ((rows '()))
    (dolist (line (uiop:split-string (or text "") :separator '(#\Newline)))
      (let ((entry (%parse-sprof-function-line line)))
        (when entry
          (push entry rows))))
    (nreverse rows)))

(defun %collect-call-graph-from-text (text)
  (let ((rows '()))
    (dolist (line (uiop:split-string (or text "") :separator '(#\Newline)))
      (let ((edge (%parse-sprof-call-edge line)))
        (when edge
          (push edge rows))))
    (nreverse rows)))

(defun %profiling-total-samples (rows)
  (loop for row in rows sum (getf row :samples 0)))

(defun %current-profiling-elapsed-ms ()
  (if (plusp *profiling-start-ms*)
      (max 0 (- (%profiling-now-ms) *profiling-start-ms*))
      0))

(defun %build-profiling-report (&key report-text)
  (let* ((text (or report-text (%capture-sprof-report-text :type :flat)))
         (parsed-top (%collect-top-functions-from-text text))
         (parsed-edges (%collect-call-graph-from-text text))
         (top-functions parsed-top)
         (call-graph parsed-edges)
         (total-samples (%profiling-total-samples parsed-top)))
    (when (or (null top-functions) (zerop total-samples))
      (multiple-value-bind (tool-top tool-total)
          (%tool-stats->top-functions)
        (setf top-functions tool-top
              total-samples tool-total)))
    (when (null call-graph)
      (setf call-graph (%tool-stats->call-graph)))
    (make-profiling-report
     :top-functions top-functions
     :call-graph call-graph
     :total-samples total-samples
     :elapsed-ms (%current-profiling-elapsed-ms)
     :raw-report-text text)))

(defun stop-profiling ()
  "Stop profiling and return the profiling-report snapshot."
  (profiler-stop)
  (setf *profiling-enabled-p* nil
        *tool-profiling-enabled-p* nil
        *last-profiling-report* (%build-profiling-report))
  *last-profiling-report*)

(defun report-profiling (&key (refresh-when-running t))
  "Return last profiling report; optionally refresh while profiler is running."
  (setf *last-profiling-report*
        (cond
          ((and refresh-when-running *profiling-enabled-p*)
           (%build-profiling-report))
          (*last-profiling-report* *last-profiling-report*)
          (t (%build-profiling-report))))
  *last-profiling-report*)

(defun %sort-key-value (entry key)
  (ecase key
    (:name (string-downcase (or (getf entry :name) "")))
    (:samples (getf entry :samples 0))
    (:percentage (getf entry :percentage 0.0d0))))

(defun sort-profiling-top-functions (entries &key (sort-by :samples) (sort-direction :desc))
  "Sort top-function entries by column."
  (let ((rows (copy-list (or entries '()))))
    (stable-sort
     rows
     (lambda (left right)
       (let ((left-value (%sort-key-value left sort-by))
             (right-value (%sort-key-value right sort-by)))
         (if (stringp left-value)
             (if (eq sort-direction :asc)
                 (string< left-value right-value)
                 (string> left-value right-value))
             (if (eq sort-direction :asc)
                 (< left-value right-value)
                 (> left-value right-value))))))))

(defun %truncate-function-name (name &key (max-width 48))
  (let ((value (or name "")))
    (if (> (length value) max-width)
        (concatenate 'string (subseq value 0 (- max-width 3)) "...")
        value)))

(defun render-profiling-report-table (&key report (sort-by :samples) (sort-direction :desc) (limit 20))
  "Render profiling report as a monospaced table suitable for TUI/CLI."
  (let* ((payload (or report *last-profiling-report*))
         (rows (and payload (profiling-report-top-functions payload))))
    (if (null rows)
        "No profiling report available. Run /profile start then /profile stop."
        (let* ((sorted (sort-profiling-top-functions rows
                                                     :sort-by sort-by
                                                     :sort-direction sort-direction))
               (selected (subseq sorted 0 (min (length sorted) (max 1 limit))))
               (name-width (max 20
                                (loop for entry in selected
                                      maximize (length (%truncate-function-name
                                                        (getf entry :name)))
                                      into width
                                      finally (return width))))
               (header (format nil
                               "~vA | ~8A | ~8A"
                               name-width
                               "FUNCTION"
                               "SAMPLES"
                               "PERCENT"))
               (divider (make-string (length header) :initial-element #\-)))
          (with-output-to-string (out)
            (format out "Profiling Report  elapsed=~Dms  total-samples=~D~%"
                    (profiling-report-elapsed-ms payload)
                    (profiling-report-total-samples payload))
            (format out "~A~%~A~%" header divider)
            (dolist (entry selected)
              (format out "~vA | ~8D | ~7,2f%%~%"
                      name-width
                      (%truncate-function-name (getf entry :name))
                      (getf entry :samples 0)
                      (coerce (getf entry :percentage 0.0d0) 'double-float))))))))

(defun %profiling-report-line-elements (&key report sort-by sort-direction limit)
  (loop for line in (uiop:split-string
                     (render-profiling-report-table
                      :report report
                      :sort-by sort-by
                      :sort-direction sort-direction
                      :limit limit)
                     :separator '(#\Newline))
        for index from 0
        collect (ptui.ui.elements:make-element
                 :text
                 :id (intern (format nil "PROFILING-TABLE-LINE-~D" index) :keyword)
                 :props (list :text line
                              :role (if (zerop index) :meta :body))
                 :children '())))

(ptui.widgets.defwidget:defwidget profiling-report-table-widget (state)
  (:memoize :equal)
  (let ((report (or (getf state :report) *last-profiling-report*))
        (sort-by (or (getf state :sort-by) :samples))
        (sort-direction (or (getf state :sort-direction) :desc))
        (limit (or (getf state :limit) 20)))
    (box
     (vstack
      (map-widget #'identity
                  (%profiling-report-line-elements
                   :report report
                   :sort-by sort-by
                   :sort-direction sort-direction
                   :limit limit)))
     :id :profiling-report-table
     :border t)))
