(asdf:defsystem "amoebum"
  :description "amoebum core application layer"
  :author "amoebum"
  :license "MIT"
  :version "0.1.0"
  :depends-on ("pseudopod" "ptui" "ptui/components" "sw4rm-sdk" "uiop" "cl-ppcre" "bordeaux-threads")
  :serial t
  :components
  ((:file "src/package")
   (:file "src/events")
   (:file "src/events/types")
   (:file "src/events/filters")
   (:file "src/config")
   (:file "src/provider-factory")
   (:file "src/context")
   (:file "src/conversation")
   (:file "src/memory")
   (:file "src/memory/haake-adapter")
   (:file "src/plan-mode")
   (:file "src/plan-execution")
   (:file "src/agents")
   (:file "src/extensions")
   (:file "src/checkpoint")
   (:file "src/sounds")
   (:file "src/commands")
   (:file "src/permissions")
   (:file "src/sandbox")
   (:file "src/sandbox-os")
   (:file "src/self-modify")
   (:file "src/asdf-extensions")
   (:file "src/reader-macros")
   (:file "src/compile-validation")
   (:file "src/macros/deftool")
   (:file "src/macros/defhook")
   (:file "src/macros/defkeys")
   (:file "src/macros/defskill")
   (:file "src/indexer")
   (:file "src/conditions")
   (:file "src/mcp/jsonrpc")
   (:file "src/mcp/server")
   (:file "src/lsp/client")
   (:file "src/mcp/tools")
   (:file "src/notifications")
   (:file "src/notifications/dispatch")
   (:file "src/pipeline")
   (:file "src/tools/files")
   (:file "src/tools/read-orchestration")
   (:file "src/tools/search")
   (:file "src/tools/search-orchestration")
   (:file "src/tools/web")
   (:file "src/tools/shell")
   (:file "src/tools/write-safety")
   (:file "src/tools/edit-validation")
   (:file "src/tools/shell-env")
   (:file "src/tools/shell-safety")
   (:file "src/tools/git")
   (:file "src/tools/lsp")
   (:file "src/profiler")
   (:file "src/widgets/fuzzy-picker")
   (:file "src/widgets/tree-browser")
   (:file "src/widgets/perf-dashboard")
   (:file "src/swarm")
   (:file "src/widgets/swarm-panel")
   (:file "src/system-prompt")
   (:file "src/ui/streaming")
   (:file "src/ui/status-bar")
   (:file "src/ui/chat")
   (:file "src/main"))
  :in-order-to ((asdf:test-op (asdf:test-op "amoebum/test"))))

(asdf:defsystem "amoebum/test"
  :description "FiveAM test suite for amoebum core application"
  :depends-on ("amoebum" "fiveam" "ptui/test-support")
  :serial t
  :components
  ((:file "test/suite")
   (:file "test/indexer-smoke-test")
   (:file "test/os-sandbox-smoke-test")
   (:file "test/self-modify-smoke-test")
   (:file "test/image-smoke-test")
   (:file "test/asdf-extensions-smoke-test")
   (:file "test/profiler-smoke-test")
   (:file "test/compile-validation-conditions-test")
   (:file "test/deftool-type-validation-test")
   (:file "test/provider-factory-test")
   (:file "test/deftool-dangerous-permission-test")
   (:file "test/pipeline-context-test")
   (:file "test/read-orchestration-test")
   (:file "test/write-safety-test")
   (:file "test/edit-validation-test")
   (:file "test/permission-path-normalization-test")
   (:file "test/permission-command-matching-test")
   (:file "test/permission-command-canonicalization-test")
   (:file "test/shell-env-test")
   (:file "test/shell-safety-test")
   (:file "test/defhook-cross-reference-test")
   (:file "test/method-combination-dispatch-test")
   (:file "test/restarts-round-trip-test")
   (:file "test/llm-restart-selection-test")
   (:file "test/event-types-test")
   (:file "test/notification-dispatch-test")
   (:file "test/stream-hooks-test")
   (:file "test/chat-snapshot-test")
   (:file "test/conversation-roundtrip-test")
   (:file "test/lifecycle-events-test"))
  :perform (asdf:test-op (op c)
             (declare (ignore op c))
             (unless (uiop:symbol-call :amoebum/test :run-all)
               (error "Amoebum FiveAM suite failed."))))
