(let* ((smoke-file (or *load-truename* *compile-file-truename*))
       (amoebum-dir (and smoke-file (make-pathname :name nil :type nil :defaults smoke-file)))
       (repo-root (and amoebum-dir (truename (merge-pathnames #P"../" amoebum-dir)))))
  (unless repo-root
    (error "Unable to resolve repository root from ~S" smoke-file))

  (load (merge-pathnames #P"ptui/.tools/quicklisp/setup.lisp" repo-root))
  (require :asdf)

  (let* ((asdf-pkg (or (find-package "ASDF")
                       (error "Missing package ASDF")))
         (load-asd-sym (or (find-symbol "LOAD-ASD" asdf-pkg)
                           (error "Missing symbol LOAD-ASD in ASDF package")))
         (load-system-sym (or (find-symbol "LOAD-SYSTEM" asdf-pkg)
                              (error "Missing symbol LOAD-SYSTEM in ASDF package")))
         (load-asd-fn (symbol-function load-asd-sym))
         (load-system-fn (symbol-function load-system-sym)))
    (funcall load-asd-fn (merge-pathnames #P"pseudopod/pseudopod.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"sw4rm-sdk/sw4rm-sdk.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"ptui/ptui.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"amoebum/amoebum.asd" repo-root))
    (funcall load-system-fn "amoebum"))

  (let* ((amoebum-pkg (or (find-package "AMOEBUM")
                          (error "Missing package AMOEBUM after load.")))
         (events-pkg (or (find-package "PTUI.CORE.EVENTS")
                         (error "Missing package PTUI.CORE.EVENTS after load.")))
         (types-pkg (or (find-package "PTUI.CORE.TYPES")
                        (error "Missing package PTUI.CORE.TYPES after load.")))
         (elements-pkg (or (find-package "PTUI.UI.ELEMENTS")
                           (error "Missing package PTUI.UI.ELEMENTS after load.")))
         (pseudopod-pkg (or (find-package "PSEUDOPOD")
                            (error "Missing package PSEUDOPOD after load.")))
         (symbol-in
           (lambda (name package)
             (or (find-symbol name package)
                 (error "Missing symbol ~A in package ~A." name (package-name package)))))
         (fn-in
           (lambda (name package)
             (symbol-function (funcall symbol-in name package))))
         (make-chat-ui-state-fn (funcall fn-in "MAKE-CHAT-UI-STATE" amoebum-pkg))
         (chat-ui-build-tree-fn (funcall fn-in "CHAT-UI-BUILD-TREE" amoebum-pkg))
         (chat-ui-add-message-fn (funcall fn-in "CHAT-UI-ADD-MESSAGE" amoebum-pkg))
         (chat-ui-submit-input-fn (funcall fn-in "CHAT-UI-SUBMIT-INPUT" amoebum-pkg))
         (chat-ui-state-input-text-fn (funcall fn-in "CHAT-UI-STATE-INPUT-TEXT" amoebum-pkg))
         (chat-ui-state-messages-fn (funcall fn-in "CHAT-UI-STATE-MESSAGES" amoebum-pkg))
         (chat-ui-state-scrollback-fn (funcall fn-in "CHAT-UI-STATE-MESSAGE-SCROLLBACK-LINES" amoebum-pkg))
         (chat-role-cell-fn (funcall fn-in "CHAT-ROLE-CELL" amoebum-pkg))
         (chat-ui-set-input-fn (funcall fn-in "CHAT-UI-SET-INPUT" amoebum-pkg))
         (render-chat-ui-buffer-fn (funcall fn-in "RENDER-CHAT-UI-BUFFER" amoebum-pkg))
         (handle-chat-ui-event-fn (funcall fn-in "HANDLE-CHAT-UI-EVENT" amoebum-pkg))
         (make-key-event-fn (funcall fn-in "MAKE-KEY-EVENT" events-pkg))
         (make-size-fn (funcall fn-in "MAKE-SIZE" types-pkg))
         (buffer-cols-fn (funcall fn-in "CELL-BUFFER-COLS" types-pkg))
         (buffer-rows-fn (funcall fn-in "CELL-BUFFER-ROWS" types-pkg))
         (buffer-cells-fn (funcall fn-in "CELL-BUFFER-CELLS" types-pkg))
         (cell-glyph-fn (funcall fn-in "CELL-GLYPH" types-pkg))
         (cell-fg-fn (funcall fn-in "CELL-FG" types-pkg))
         (ui-element-type-fn (funcall fn-in "UI-ELEMENT-TYPE" elements-pkg))
         (ui-element-children-fn (funcall fn-in "UI-ELEMENT-CHILDREN" elements-pkg))
         (message-role-fn (funcall fn-in "MESSAGE-ROLE" pseudopod-pkg))
         (message-content-fn (funcall fn-in "MESSAGE-CONTENT" pseudopod-pkg))
         (content-part-text-fn (funcall fn-in "CONTENT-PART-TEXT" pseudopod-pkg)))
    (labels ((assert-true (condition format-string &rest format-args)
               (unless condition
                 (error (apply #'format nil format-string format-args))))
             (tree-has-type-p (node type)
               (or (eq (funcall ui-element-type-fn node) type)
                   (some (lambda (child)
                           (tree-has-type-p child type))
                         (funcall ui-element-children-fn node))))
             (buffer-cell-at (buffer col row)
               (let* ((cols (funcall buffer-cols-fn buffer))
                      (cells (funcall buffer-cells-fn buffer))
                      (index (+ col (* row cols))))
                 (svref cells index)))
             (buffer-lines (buffer)
               (let* ((cols (funcall buffer-cols-fn buffer))
                      (rows (funcall buffer-rows-fn buffer)))
                 (loop for row from 0 below rows
                       collect
                       (with-output-to-string (out)
                         (loop for col from 0 below cols do
                           (let ((glyph (funcall cell-glyph-fn
                                                 (buffer-cell-at buffer col row))))
                             (when (> (length glyph) 0)
                               (write-string glyph out))))))))
             (rows-contain-p (rows text)
               (loop for row in rows
                     thereis (search text row :test #'char-equal)))
             (find-prefix-position (rows prefix)
               (loop for row-text in rows
                     for row-index from 0 do
                       (let ((col-index (search prefix row-text :test #'char-equal)))
                         (when col-index
                           (return (values row-index col-index))))))
             (prefix-fg-string (buffer prefix)
               (let ((rows (buffer-lines buffer)))
                 (multiple-value-bind (row col)
                     (find-prefix-position rows prefix)
                   (when (and row col)
                     (let ((cell (buffer-cell-at buffer col row)))
                       (prin1-to-string (funcall cell-fg-fn cell)))))))
             (message-text (message)
               (with-output-to-string (out)
                 (loop for part in (funcall message-content-fn message)
                       for index from 0 do
                         (when (> index 0)
                           (write-char #\Newline out))
                         (write-string (or (funcall content-part-text-fn part) "")
                                       out))))
             (make-chat-state ()
               (funcall make-chat-ui-state-fn :stream-runner nil))
             (make-text-event (text)
               (funcall make-key-event-fn :text :text? text)))
      (let ((tree (funcall chat-ui-build-tree-fn
                           (make-chat-state)
                           100
                           24)))
        (assert-true (tree-has-type-p tree :prompt-box)
                     "Expected chat UI tree to include a prompt-box widget."))

      (let ((state (make-chat-state)))
        (funcall chat-ui-add-message-fn state :system "System primed.")
        (funcall chat-ui-add-message-fn state :user "Show me the diff.")
        (funcall chat-ui-add-message-fn state :assistant "I found 3 changed files.")
        (let* ((buffer (funcall render-chat-ui-buffer-fn
                                state
                                (funcall make-size-fn 110 24)))
               (rows (buffer-lines buffer))
               (user-fg (prefix-fg-string buffer "YOU>"))
               (assistant-fg (prefix-fg-string buffer "ASSISTANT>"))
               (system-fg (prefix-fg-string buffer "SYSTEM>")))
          (assert-true (rows-contain-p rows "YOU> Show me the diff.")
                       "Expected rendered history to include user role prefix/text.")
          (assert-true (rows-contain-p rows "ASSISTANT> I found 3 changed files.")
                       "Expected rendered history to include assistant role prefix/text.")
          (assert-true (rows-contain-p rows "SYSTEM> System primed.")
                       "Expected rendered history to include system role prefix/text.")
          (assert-true (and user-fg assistant-fg system-fg)
                       "Expected to locate role-specific styled cells in rendered buffer.")
          (assert-true (not (string= user-fg assistant-fg))
                       "Expected user and assistant role styles to differ.")
          (assert-true (not (string= user-fg system-fg))
                       "Expected user and system role styles to differ.")
          (assert-true (not (string= assistant-fg system-fg))
                       "Expected assistant and system role styles to differ.")))

      (let ((state (make-chat-state)))
        (funcall render-chat-ui-buffer-fn state (funcall make-size-fn 70 16))
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "h")))
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "i")))
        (assert-true (string= (funcall chat-ui-state-input-text-fn state) "hi")
                     "Expected prompt input text to accumulate keystrokes.")
        (setf state (funcall handle-chat-ui-event-fn state (funcall make-key-event-fn :enter)))
        (assert-true (string= (funcall chat-ui-state-input-text-fn state) "")
                     "Expected Enter submission to clear prompt input.")
        (let* ((messages (funcall chat-ui-state-messages-fn state))
               (last-message (car (last messages))))
          (assert-true last-message
                       "Expected submitted input to append a user message.")
          (assert-true (string= (funcall message-role-fn last-message) "user")
                       "Expected submitted message role to be user.")
          (assert-true (string= (message-text last-message) "hi")
                       "Expected submitted message content to match prompt text."))
        (funcall chat-ui-set-input-fn state "manual submit")
        (funcall chat-ui-submit-input-fn state)
        (assert-true (>= (length (funcall chat-ui-state-messages-fn state)) 2)
                     "Expected CHAT-UI-SUBMIT-INPUT to append user message."))

      (let ((state (make-chat-state)))
        (loop for index from 1 to 30 do
          (funcall chat-ui-add-message-fn
                   state
                   :assistant
                   (format nil "entry-~D" index)))
        (let* ((size (funcall make-size-fn 60 10))
               (bottom-buffer (funcall render-chat-ui-buffer-fn state size))
               (bottom-rows (buffer-lines bottom-buffer)))
          (assert-true (rows-contain-p bottom-rows "entry-30")
                       "Expected default history view to show newest messages.")
          (dotimes (n 20)
            (declare (ignore n))
            (setf state (funcall handle-chat-ui-event-fn
                                 state
                                 (funcall make-key-event-fn :pgup))))
          (let* ((top-buffer (funcall render-chat-ui-buffer-fn state size))
                 (top-rows (buffer-lines top-buffer)))
            (assert-true (> (funcall chat-ui-state-scrollback-fn state) 0)
                         "Expected PgUp to increase message scrollback.")
            (assert-true (rows-contain-p top-rows "entry-1")
                         "Expected scrolled history view to reach older messages."))
          (dotimes (n 20)
            (declare (ignore n))
            (setf state (funcall handle-chat-ui-event-fn
                                 state
                                 (funcall make-key-event-fn :pgdn))))
          (let* ((bottom-again-buffer (funcall render-chat-ui-buffer-fn state size))
                 (bottom-again-rows (buffer-lines bottom-again-buffer)))
            (assert-true (= (funcall chat-ui-state-scrollback-fn state) 0)
                         "Expected PgDn to return history scrollback to newest.")
            (assert-true (rows-contain-p bottom-again-rows "entry-30")
                         "Expected returned history view to show newest message again.")))))

  (format t "AMOEBUM_CHAT_UI_SMOKE_OK~%")))
