(let* ((smoke-file (or *load-truename* *compile-file-truename*))
       (amoebum-dir (and smoke-file (make-pathname :name nil :type nil :defaults smoke-file)))
       (repo-root (and amoebum-dir (truename (merge-pathnames #P"../" amoebum-dir)))))
  (unless repo-root
    (error "Unable to resolve repository root from ~S" smoke-file))

  (load (merge-pathnames #P"ptui/.tools/quicklisp/setup.lisp" repo-root))
  (require :asdf)

  (let* ((asdf-pkg (or (find-package "ASDF")
                       (error "Missing package ASDF")))
         (load-asd-sym (or (find-symbol "LOAD-ASD" asdf-pkg)
                           (error "Missing symbol LOAD-ASD in ASDF package")))
         (load-system-sym (or (find-symbol "LOAD-SYSTEM" asdf-pkg)
                              (error "Missing symbol LOAD-SYSTEM in ASDF package")))
         (load-asd-fn (symbol-function load-asd-sym))
         (load-system-fn (symbol-function load-system-sym)))
    (funcall load-asd-fn (merge-pathnames #P"pseudopod/pseudopod.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"ptui/ptui.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"amoebum/amoebum.asd" repo-root))
    (funcall load-system-fn "amoebum"))

  (let* ((amoebum-pkg (or (find-package "AMOEBUM")
                          (error "Missing package AMOEBUM after load.")))
         (pseudopod-pkg (or (find-package "PSEUDOPOD")
                            (error "Missing package PSEUDOPOD after load.")))
         (symbol-in
           (lambda (name package)
             (or (find-symbol name package)
                 (error "Missing symbol ~A in package ~A." name (package-name package)))))
         (fn-in
           (lambda (name package)
             (symbol-function (funcall symbol-in name package))))
         (make-toolset-fn (funcall fn-in "MAKE-TOOLSET" pseudopod-pkg))
         (find-tool-fn (funcall fn-in "FIND-TOOL" pseudopod-pkg))
         (tool-definition-parameters-fn (funcall fn-in "TOOL-DEFINITION-PARAMETERS" pseudopod-pkg))
         (tool-definition-fn-fn (funcall fn-in "TOOL-DEFINITION-FN" pseudopod-pkg))
         (toolset-sym (funcall symbol-in "*TOOLSET*" amoebum-pkg))
         (tool-metadata-sym (funcall symbol-in "*TOOL-METADATA*" amoebum-pkg))
         (tool-metadata-permission-fn (funcall fn-in "TOOL-METADATA-PERMISSION" amoebum-pkg))
         (tool-metadata-dangerous-p-fn (funcall fn-in "TOOL-METADATA-DANGEROUS-P" amoebum-pkg))
         (tool-metadata-category-fn (funcall fn-in "TOOL-METADATA-CATEGORY" amoebum-pkg))
         (tool-metadata-timeout-fn (funcall fn-in "TOOL-METADATA-TIMEOUT-SECONDS" amoebum-pkg))
         (deftool-sym (funcall symbol-in "DEFTOOL" amoebum-pkg))
         (cl-type-to-json-schema-fn (funcall fn-in "CL-TYPE-TO-JSON-SCHEMA" amoebum-pkg)))
    (labels ((assert-true (condition format-string &rest format-args)
               (unless condition
                 (error (apply #'format nil format-string format-args))))
             (contains-symbol-p (tree target)
               (cond
                 ((eq tree target) t)
                 ((consp tree)
                  (or (contains-symbol-p (car tree) target)
                      (contains-symbol-p (cdr tree) target)))
                 (t nil)))
             (as-list (value)
               (cond
                 ((null value) nil)
                 ((listp value) value)
                 ((vectorp value) (loop for item across value collect item))
                 (t (list value)))))
      (let* ((expand-form
               `(,deftool-sym i26-expand-check
                  ((path pathname :description "Path to read" :required t)
                   (offset (or null integer) :description "Offset" :default nil))
                  "Expansion check tool"
                  (:permission :auto)
                  (:dangerous nil)
                  (:category :test)
                  (:timeout 5)
                  (list path offset)))
             (expanded (macroexpand-1 expand-form)))
        (assert-true (and (consp expanded) (eq (car expanded) 'progn))
                     "Expected deftool macroexpansion to be a PROGN.")
        (assert-true (contains-symbol-p expanded 'defun)
                     "Expected deftool expansion to include DEFUN.")
        (assert-true (contains-symbol-p expanded
                                        (funcall symbol-in "REGISTER-TOOL" pseudopod-pkg))
                     "Expected deftool expansion to include PSEUDOPOD:REGISTER-TOOL.")
        (assert-true (contains-symbol-p expanded
                                        (funcall symbol-in "MAKE-TOOL-DEFINITION" pseudopod-pkg))
                     "Expected deftool expansion to include PSEUDOPOD:MAKE-TOOL-DEFINITION.")
        (assert-true (contains-symbol-p expanded
                                        (funcall symbol-in "MAKE-TOOL-METADATA" amoebum-pkg))
                     "Expected deftool expansion to include metadata construction."))

      (setf (symbol-value toolset-sym) (funcall make-toolset-fn))
      (clrhash (symbol-value tool-metadata-sym))

      (eval
       `(,deftool-sym i26-schema-check
          ((path pathname :description "Absolute path" :required t)
           (limit (or null integer) :description "Line limit" :default nil)
           (dry-run boolean :description "Dry run" :default nil)
           (mode (member :fast :slow) :description "Mode" :default :fast))
          "Schema and registration smoke tool"
          (:permission :auto)
          (:dangerous t)
          (:category :smoke)
          (:timeout 9)
          (list :path-is-pathname (pathnamep path)
                :limit limit
                :dry-run dry-run
                :mode mode)))

      (let* ((toolset (symbol-value toolset-sym))
             (tool (funcall find-tool-fn toolset "i26-schema-check")))
        (assert-true tool
                     "Expected deftool registration to place tool in the active toolset.")
        (let* ((schema (funcall tool-definition-parameters-fn tool))
               (properties (gethash "properties" schema))
               (required (as-list (gethash "required" schema)))
               (path-schema (gethash "path" properties))
               (limit-schema (gethash "limit" properties))
               (dry-run-schema (gethash "dry-run" properties))
               (mode-schema (gethash "mode" properties))
               (limit-types (as-list (gethash "type" limit-schema)))
               (mode-enum (as-list (gethash "enum" mode-schema))))
          (assert-true (string= (gethash "type" path-schema) "string")
                       "Expected pathname to map to JSON schema string type.")
          (assert-true (string= (gethash "format" path-schema) "path")
                       "Expected pathname to include JSON schema format=path.")
          (assert-true (member "integer" limit-types :test #'string=)
                       "Expected (or null integer) to include integer JSON type.")
          (assert-true (member "null" limit-types :test #'string=)
                       "Expected (or null integer) to include null JSON type.")
          (assert-true (string= (gethash "type" dry-run-schema) "boolean")
                       "Expected boolean type to map to JSON schema boolean.")
          (assert-true (string= (gethash "type" mode-schema) "string")
                       "Expected member type to map to JSON schema string.")
          (assert-true (and (member "fast" mode-enum :test #'string=)
                            (member "slow" mode-enum :test #'string=))
                       "Expected member enum values to map to lowercase strings.")
          (assert-true (member "path" required :test #'string=)
                       "Expected :required t parameter to appear in required list."))

        (let* ((fn (funcall tool-definition-fn-fn tool))
               (args (make-hash-table :test #'equal)))
          (setf (gethash "path" args) "/tmp/smoke.txt")
          (setf (gethash "limit" args) "3")
          (setf (gethash "dry-run" args) "true")
          (setf (gethash "mode" args) "slow")
          (let ((result (funcall fn args)))
            (assert-true (equal (getf result :path-is-pathname) t)
                         "Expected generated function to coerce pathname argument.")
            (assert-true (eql (getf result :limit) 3)
                         "Expected generated function to coerce integer argument.")
            (assert-true (equal (getf result :dry-run) t)
                         "Expected generated function to coerce boolean argument.")
            (assert-true (eq (getf result :mode) :slow)
                         "Expected member argument coercion to return member symbol."))))

      (let ((metadata (gethash "i26-schema-check" (symbol-value tool-metadata-sym))))
        (assert-true metadata
                     "Expected metadata record to be registered for deftool.")
        (assert-true (eq (funcall tool-metadata-permission-fn metadata) :auto)
                     "Expected metadata permission to match declaration.")
        (assert-true (eq (funcall tool-metadata-dangerous-p-fn metadata) t)
                     "Expected metadata dangerous flag to match declaration.")
        (assert-true (eq (funcall tool-metadata-category-fn metadata) :smoke)
                     "Expected metadata category to match declaration.")
        (assert-true (= (funcall tool-metadata-timeout-fn metadata) 9)
                     "Expected metadata timeout to match declaration."))

      (let* ((schema (funcall cl-type-to-json-schema-fn '(or null integer)))
             (types (as-list (gethash "type" schema))))
        (assert-true (and (member "integer" types :test #'string=)
                          (member "null" types :test #'string=))
                     "Expected CL type mapper to support (or null integer)."))))

  (format t "AMOEBUM_DEFTOOL_SMOKE_OK~%"))
