(let* ((smoke-file (or *load-truename* *compile-file-truename*))
       (amoebum-dir (and smoke-file (make-pathname :name nil :type nil :defaults smoke-file)))
       (repo-root (and amoebum-dir (truename (merge-pathnames #P"../" amoebum-dir)))))
  (unless repo-root
    (error "Unable to resolve repository root from ~S" smoke-file))

  (load (merge-pathnames #P"ptui/.tools/quicklisp/setup.lisp" repo-root))
  (require :asdf)

  (let* ((asdf-pkg (or (find-package "ASDF")
                       (error "Missing package ASDF")))
         (load-asd-sym (or (find-symbol "LOAD-ASD" asdf-pkg)
                           (error "Missing symbol LOAD-ASD in ASDF package")))
         (load-system-sym (or (find-symbol "LOAD-SYSTEM" asdf-pkg)
                              (error "Missing symbol LOAD-SYSTEM in ASDF package")))
         (load-asd-fn (symbol-function load-asd-sym))
         (load-system-fn (symbol-function load-system-sym)))
    (funcall load-asd-fn (merge-pathnames #P"pseudopod/pseudopod.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"ptui/ptui.asd" repo-root))
    (funcall load-asd-fn (merge-pathnames #P"amoebum/amoebum.asd" repo-root))
    (funcall load-system-fn "amoebum"))

  (let* ((amoebum-pkg (or (find-package "AMOEBUM")
                          (error "Missing package AMOEBUM after load.")))
         (events-pkg (or (find-package "PTUI.CORE.EVENTS")
                         (error "Missing package PTUI.CORE.EVENTS after load.")))
         (types-pkg (or (find-package "PTUI.CORE.TYPES")
                        (error "Missing package PTUI.CORE.TYPES after load.")))
         (pseudopod-pkg (or (find-package "PSEUDOPOD")
                            (error "Missing package PSEUDOPOD after load.")))
         (symbol-in
           (lambda (name package)
             (or (find-symbol name package)
                 (error "Missing symbol ~A in package ~A." name (package-name package)))))
         (fn-in
           (lambda (name package)
             (symbol-function (funcall symbol-in name package))))
         (make-chat-ui-state-fn (funcall fn-in "MAKE-CHAT-UI-STATE" amoebum-pkg))
         (render-chat-ui-buffer-fn (funcall fn-in "RENDER-CHAT-UI-BUFFER" amoebum-pkg))
         (handle-chat-ui-event-fn (funcall fn-in "HANDLE-CHAT-UI-EVENT" amoebum-pkg))
         (chat-ui-state-messages-fn (funcall fn-in "CHAT-UI-STATE-MESSAGES" amoebum-pkg))
         (chat-ui-state-stream-state-fn (funcall fn-in "CHAT-UI-STATE-STREAM-STATE" amoebum-pkg))
         (token-stream-emit-chunk-fn (funcall fn-in "TOKEN-STREAM-EMIT-CHUNK" amoebum-pkg))
         (token-stream-progress-summary-fn (funcall fn-in "TOKEN-STREAM-PROGRESS-SUMMARY" amoebum-pkg))
         (make-key-event-fn (funcall fn-in "MAKE-KEY-EVENT" events-pkg))
         (make-size-fn (funcall fn-in "MAKE-SIZE" types-pkg))
         (buffer-cols-fn (funcall fn-in "CELL-BUFFER-COLS" types-pkg))
         (buffer-rows-fn (funcall fn-in "CELL-BUFFER-ROWS" types-pkg))
         (buffer-cells-fn (funcall fn-in "CELL-BUFFER-CELLS" types-pkg))
         (cell-glyph-fn (funcall fn-in "CELL-GLYPH" types-pkg))
         (message-role-fn (funcall fn-in "MESSAGE-ROLE" pseudopod-pkg))
         (message-content-fn (funcall fn-in "MESSAGE-CONTENT" pseudopod-pkg))
         (content-part-text-fn (funcall fn-in "CONTENT-PART-TEXT" pseudopod-pkg)))
    (labels
        ((assert-true (condition format-string &rest format-args)
           (unless condition
             (error (apply #'format nil format-string format-args))))
         (buffer-cell-at (buffer col row)
           (let* ((cols (funcall buffer-cols-fn buffer))
                  (cells (funcall buffer-cells-fn buffer))
                  (index (+ col (* row cols))))
             (svref cells index)))
         (buffer-lines (buffer)
           (let* ((cols (funcall buffer-cols-fn buffer))
                  (rows (funcall buffer-rows-fn buffer)))
             (loop for row from 0 below rows
                   collect
                   (with-output-to-string (out)
                     (loop for col from 0 below cols do
                       (let ((glyph (funcall cell-glyph-fn
                                             (buffer-cell-at buffer col row))))
                         (when (> (length glyph) 0)
                           (write-string glyph out))))))))
         (rows-contain-p (rows text)
           (loop for row in rows
                 thereis (search text row :test #'char-equal)))
         (message-text (message)
           (with-output-to-string (out)
             (loop for part in (funcall message-content-fn message)
                   for index from 0 do
                     (when (> index 0)
                       (write-char #\Newline out))
                     (write-string (or (funcall content-part-text-fn part) "") out))))
         (last-assistant-text (state)
           (let ((assistant-message
                   (find-if (lambda (message)
                              (string= (funcall message-role-fn message) "assistant"))
                            (funcall chat-ui-state-messages-fn state)
                            :from-end t)))
             (and assistant-message
                  (message-text assistant-message))))
         (make-text-event (text)
           (funcall make-key-event-fn :text :text? text)))
      (let* ((runner
               (lambda (stream-state prompt messages &key system-prompt client tools)
                 (declare (ignore prompt messages system-prompt client tools))
                 (funcall token-stream-emit-chunk-fn stream-state "Hello ")
                 (sleep 0.2d0)
                 (funcall token-stream-emit-chunk-fn stream-state "world")))
             (state (funcall make-chat-ui-state-fn :stream-runner runner))
             (size (funcall make-size-fn 100 20)))
        (funcall render-chat-ui-buffer-fn state size)
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "h")))
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "i")))
        (setf state (funcall handle-chat-ui-event-fn state (funcall make-key-event-fn :enter)))
        (sleep 0.05d0)
        (let* ((buffer (funcall render-chat-ui-buffer-fn state size))
               (rows (buffer-lines buffer))
               (assistant-text (or (last-assistant-text state) "")))
          (assert-true (search "Hello " assistant-text :test #'char-equal)
                       "Expected first streamed chunk to appear incrementally.")
          (assert-true (rows-contain-p rows "tok/s")
                       "Expected status line to include tok/s during active stream."))
        (sleep 0.25d0)
        (funcall render-chat-ui-buffer-fn state size)
        (let* ((assistant-text (or (last-assistant-text state) ""))
               (summary (funcall token-stream-progress-summary-fn
                                 (funcall chat-ui-state-stream-state-fn state))))
          (assert-true (string= assistant-text "Hello world")
                       "Expected assistant text to include all streamed chunks, got ~S."
                       assistant-text)
          (assert-true (eq (getf summary :status) :completed)
                       "Expected stream status :COMPLETED, got ~S."
                       (getf summary :status))))

      (let* ((runner
               (lambda (stream-state prompt messages &key system-prompt client tools)
                 (declare (ignore prompt messages system-prompt client tools))
                 (funcall token-stream-emit-chunk-fn stream-state "partial ")
                 (sleep 0.30d0)
                 (funcall token-stream-emit-chunk-fn stream-state "tail")))
             (state (funcall make-chat-ui-state-fn :stream-runner runner))
             (size (funcall make-size-fn 100 20)))
        (funcall render-chat-ui-buffer-fn state size)
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "c")))
        (setf state (funcall handle-chat-ui-event-fn state (make-text-event "x")))
        (setf state (funcall handle-chat-ui-event-fn state (funcall make-key-event-fn :enter)))
        (sleep 0.05d0)
        (funcall render-chat-ui-buffer-fn state size)
        (setf state (funcall handle-chat-ui-event-fn state (funcall make-key-event-fn :ctrl-c :ctrlp t)))
        (sleep 0.35d0)
        (funcall render-chat-ui-buffer-fn state size)
        (let* ((assistant-text (or (last-assistant-text state) ""))
               (summary (funcall token-stream-progress-summary-fn
                                 (funcall chat-ui-state-stream-state-fn state))))
          (assert-true (string= assistant-text "partial ")
                       "Expected cancellation to preserve partial assistant output, got ~S."
                       assistant-text)
          (assert-true (eq (getf summary :status) :cancelled)
                       "Expected stream status :CANCELLED, got ~S."
                       (getf summary :status))))))

  (format t "AMOEBUM_STREAMING_SMOKE_OK~%"))
